### ISSUE TITLE
Essential-Addons-Pro <-> Gravity Forms Signature Addon

### ISSUE THREAD

**Issue by SvenAdam** [WPDevelopers/essential-addons-for-elementor-lite#139]
Effect: 
on both addons activated, form fields don't show up (while some headlines do, when form is added thru EA gravityforms widget, e. g.). Gravityforms without EA works fine.

Solution:
get gravityforms to work at all with EA: switch off gravityforms signature add-on. Form will show then. Function not tested yet. 

Testing: 
approved by conflict approximation thru theme / plugin switching

Request: In case you can reproduce, get in touch with GF signature add-on guys and wipe out the conflict. EA widget to have GF forms in Elementor page is as needed as the graphic signature field provided by that GF add-on.

- - -

Setup:
### Gravity Forms ###

Registration: Not registered ✘ 
Version: 2.4.5 ✔
Upload folder: /var/www/vhosts/roaddoc.de/httpdocs/wp-content/uploads/gravity_forms/
Upload folder permissions: Writable  ✔
Output CSS: No
Output HTML5: No
No-Conflict Mode: Yes
Currency: EUR
Background updates: Yes
Locale: de_DE

### Add-Ons ###

GP Nested Forms: by David Smith - 1.0-beta-6.16  ✔
GP Populate Anything: by Gravity Wiz - 1.0-beta-2.1  ✔
Chained Selects: by rocketgenius - 1.1  ✔
CLI: by Rocketgenius - 1.1  ✔
Partial Entries: by rocketgenius - 1.3  ✔
REST API: by Rocketgenius - 2.0-rc-1  ✔
Survey: by rocketgenius - 3.3  ✔
User Registration: by rocketgenius - 4.0  ✔
Webhooks: by rocketgenius - 1.1  ✔
SP WPDB Connect: by Ralf Fuhrmann - 3.5.1  ✔

### Database ###

Database Version: 2.4.5  ✔ Your database is up-to-date.
RD_gf_form_view:   ✔
RD_gf_form_meta:   ✔
RD_gf_form:   ✔
RD_gf_form_revisions:   ✔
RD_gf_entry:   ✔
RD_gf_entry_meta:   ✔
RD_gf_entry_notes:   ✔
RD_gf_draft_submissions:   ✔
RD_gf_addon_feed:   ✔

### WordPress ###

Home URL: https://www.roaddoc.de
Site URL: https://www.roaddoc.de
WordPress Version: 5.0.3 ✔
WordPress Multisite: No
WordPress Memory Limit: 40M
WordPress Debug Mode: No
WordPress Debug Log: No
WordPress Script Debug Mode: No
WordPress Cron: Yes
WordPress Alternate Cron: No
Background tasks: No ✘ cURL error 28: Operation timed out after 2001 milliseconds with 0 out of -1 bytes received

### Active Theme ###

OceanWP: by Nick (https://oceanwp.org/about-me/) - 1.6.1  ✔

### Active Plugins ###

Amelia: by TMS - 1.4  ✔
Asset CleanUp Pro: Page Speed Booster: by Gabriel Livan - 1.1.0.4  ✔
Checkout Field Editor for WooCommerce: by ThemeHiGH - 2.9.8  ✔
Classic Editor: by WordPress Contributors - 1.3  ✔
Code Snippets: by Shea Bunge - 2.13.0  ✔
Duplicate Post: by Enrico Battocchi - 3.2.2  ✔
Elementor: by Elementor.com - 2.4.1  ✔
Elementor Pro: by Elementor.com - 2.3.1  ✔
Email Verification / SMS verification / Mobile Verification: by miniOrange - 11.5.25  ✔
Essential Addons for Elementor - Pro: by WPDeveloper - 2.14.0  ✔
gAppointments: by WpCrunch - 1.9.1  ✔
German Market: by MarketPress - 3.5.8  ✔
GP Auto Login: by David Smith - 1.3.4  ✔
GP Better User Activation: by Gravity Wiz - 1.1.7  ✔
GP Conditional Pricing: by Gravity Wiz - 1.2.37  ✔
GP eCommerce Fields: by Gravity Wiz - 1.0.24  ✔
GP Media Library: by Gravity Wiz - 1.0.14  ✔
GP Multi-page Navigation: by Gravity Wiz - 1.0.4  ✔
GP Post Content Merge Tags: by David Smith - 1.1.8  ✔
GP Read Only: by David Smith - 1.3.5  ✔
GP Reload Form: by David Smith - 1.1.17  ✔
GP Unique ID: by David Smith - 1.3.14  ✔
Gravity Perks: by Gravity Wiz - 2.1.2  ✔
Health Check & Troubleshooting: by The WordPress.org community - 1.2.4  ✔
miniOrange 2 Factor Authentication: by miniOrange - 12.4.2-premium  ✔
Multiple Addresses for Woocommerce: by ThemeHigh - 1.0.5  ✔
Ocean Cookie Notice: by OceanWP - 1.0.4  ✔
Ocean Elementor Widgets: by OceanWP - 1.1.3  ✔
Ocean Extra: by OceanWP - 1.5.0  ✔
Ocean Footer Callout: by OceanWP - 1.0.13  ✔
Ocean Full Screen: by OceanWP - 1.0.4  ✔
Ocean Hooks: by OceanWP - 1.1.2  ✔
Ocean Popup Login: by OceanWP - 1.0.5  ✔
Ocean Side Panel: by OceanWP - 1.0.11  ✔
Ocean Sticky Footer: by OceanWP - 1.0.9  ✔
Ocean Sticky Header: by OceanWP - 1.1.11  ✔
Ocean White Label: by OceanWP - 1.0.5  ✔
Ocean Woo Popup: by OceanWP - 1.0.6  ✔
Orbit Fox Companion: by Themeisle - 2.7.3  ✔
PayPal Plus for WooCommerce: by Inpsyde GmbH - 1.0.8  ✔
Post SMTP: by Jason Hendriks, Yehuda Hassine - 1.9.5  ✔
Rank Math SEO: by MyThemeShop - 1.0.12  ✔
Really Simple SSL: by Rogier Lankhorst, Mark Wolters - 3.1.3  ✔
Really Simple SSL pro: by Rogier Lankhorst - 2.0.23  ✔
Report Builder for wpDataTables: by TMS-Plugins - 1.1.4  ✔
Shariff Wrapper: by Jan-Peter Lambeck & 3UU - 4.5.3  ✔
Social Login, Social Sharing by miniOrange: by social login (miniOrange) - 7.1.3  ✔
TinyMCE Advanced: by Andrew Ozz - 5.0.0  ✔
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com, DavidAnderson - 2.16.3.24  ✔
User Role Editor: by Vladimir Garagulya - 4.49  ✔
Webcraftic Disable Admin Notices Individually: by Webcraftic  - 1.0.6  ✔
Wicked Folders: by Wicked Plugins - 2.11.0  ✔
WooCommerce: by Automattic - 3.5.3  ✔
WooCommerce Composite Products: by SomewhereWarm - 3.15.0  ✔
WooCommerce Force Sells: by WooCommerce - 1.1.16  ✔
WooCommerce PayPal Checkout Gateway: by WooCommerce - 1.6.6  ✔
WooCommerce Role Based Methods: by WPBackOffice - 2.3.10  ✔
WooCommerce Services: by Automattic - 1.18.0  ✔
WooCommerce Stripe Gateway: by WooCommerce - 4.1.14  ✔
wpDataTables: by TMS-Plugins - 2.3.2  ✔
WP HTML Mail: by Hannes Etzelstorfer - 2.8.4.2  ✔
WP HTML Mail - WooCommerce: by Hannes Etzelstorfer - 2.8.3  ✔
WP Security Pro: by miniorange - 21.2.0  ✔
YITH WooCommerce Customize My Account Page: by YITH - 2.5.3  ✔

### Web Server ###

Software: Apache
Port: 443
Document Root: /var/www/vhosts/roaddoc.de/httpdocs

### PHP ###

Version: 7.1.26 ✔
Memory Limit: 256M
Maximum Execution Time: 600
Maximum File Upload Size: 32M
Maximum File Uploads: 20
Maximum Post Size: 32M
Maximum Input Variables: 5000
cURL Enabled: Yes (Version 7.29.0)
OpenSSL: OpenSSL 1.0.1e 11 Feb 2013 (268439647)
Mcrypt Enabled: Yes
Mbstring Enabled: Yes
Loaded Extensions: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

### MySQL ###

Version: 5.7.24 ✔
Database Character Set: utf8
Database Collation: utf8_general_ci

**Comment by drinky** [comment]
How did you go with this Sven? Did you get it resolved. We've having javascript issues between EA and Gravity Forms and it turns out to be disabling the signature addon that resolves the issue.

**Comment by SvenAdam** [comment]
Hi Brett,

 

not good actually. Even with signature addon deactivated the Toggle widget doesn’t offer a choice for the second switch position when ‘templates’ have been selected.

Beyond that I am constantly asked to activate the plugin despite the fact that I did so several times. Currently I receive cURL 28 errors when trying to activate.

 

 

regards,

 

Sven Adam

 

Von: Brett Drinkwater [mailto:notifications@github.com] 
Gesendet: Sonntag, 23. Juni 2019 12:43
An: rupok/essential-addons-for-elementor-lite <essential-addons-for-elementor-lite@noreply.github.com>
Cc: SvenAdam <webmaster@roaddoc.de>; Author <author@noreply.github.com>
Betreff: Re: [rupok/essential-addons-for-elementor-lite] Essential-Addons-Pro <-> Gravity Forms Signature Addon (#139)

 

How did you go with this Sven? Did you get it resolved. We've having javascript issues between EA and Gravity Forms and it turns out to be disabling the signature addon that resolves the issue.
