### ISSUE TITLE
No dynamics fields in the Image comparison

### ISSUE THREAD

**Issue by vgstef** [WPDevelopers/essential-addons-for-elementor-lite#339]
Hi,

I'm a pro user. I'm using the "EA Image Comparison". But it's missing the dynamic field support for the images.

In May 2018, the changelog said "Dynamic field support added to all elements" (https://essential-addons.com/elementor/changelog/)

So could you add the dynamic field to the Image Comparison?

Thanks

**Comment by khan-rafin-ahmed** [comment]
@vgstef,

It has been fixed in the recent update. Thank you!
