### ISSUE TITLE
Image HotSpot and Dynamic values

### ISSUE THREAD

**Issue by GerardPerret** [WPDevelopers/essential-addons-for-elementor-lite#470]
Hi,
I am testing Image HotSpot using Elementor PRO 2.9.0 Beta2 and i am not able to get any value when i Use a dynamic value from a Custom Field or even from a regular field.

I tried to set the tooltip text (image2) as well as the tooltip background and text colour but can't get the expected result.

Any idea?
Thanks

![HotSpot1](https://user-images.githubusercontent.com/42167940/76555249-915f4280-6497-11ea-86f6-c6b735d66bd1.jpg)
![HotSpot2](https://user-images.githubusercontent.com/42167940/76555251-91f7d900-6497-11ea-9c00-6fb8931320fb.jpg)

**Comment by GerardPerret** [comment]
Hello there, any chance to get this feature somehow, an email from support was saying that this should be done, it's not yet and now is coming for me the renewal license time, it would be great to know if this will be done.
Thanks

**Comment by IftekharPial** [comment]
Hello there,

Hope you are doing well.

You will be glad to know that Our latest version of Essential Addons Fully supports ACF in the EA Image Hotspot.

Please update to the latest version of Essential Addons and your issues will be fixed

Hope it helps

Thanks
