### ISSUE TITLE
EA Feature List - Dynamic header link incorrect

### ISSUE THREAD

**Issue by momania** [WPDevelopers/essential-addons-for-elementor-lite#471]
When setting the the link on an EA Feature List, it leaves the `http(s)://` prefix.
This results in a broken href attribute of the header element.

i.e.
```html
<a href="http://%23elementor-action%3Aaction%3Dpopup%3Aopen%26settings%3DeyJpZCI6IjM0OCIsInRvZ2dsZSI6ZmFsc2V9">My Header</a>
```

The linked icon has the correct attribute value set:
```html
<a class="eael-feature-list-icon" href="%23elementor-action%3Aaction%3Dpopup%3Aopen%26settings%3DeyJpZCI6IjM0OCIsInRvZ2dsZSI6ZmFsc2V9">
    <i class="fas fa-plus" aria-hidden="true"></i>
</a>
```

**Comment by shamserSuzon** [comment]
Hi there,

I have tested the issue and couldn't reproduce it. Please, make sure you are using the latest versions of the Free ( 3.8.5 ) & Pro ( 3.5.3 ) plugins. It should work fine.

Let me know, please.

**Comment by momania** [comment]
Ah sorry, I forgot to mention explicitly that this is only the case with a dynamic link. In my case I'm trying to set it to link to a popup.

A normal url link works fine.

**Comment by shamserSuzon** [comment]
Hi there,

Before giving my last message, I have already tested with the dynamic links and couldn't reproduce any such issue. Could you please record me reproducing your issue using a tool like this? https://www.loom.com 

It helps me to quickly figure out the issue and squash it immediately. 

Thank you.

**Comment by momania** [comment]
I hope this helps:

Creating a standard feature list, setting url to dynamic - popup
<img width="500" alt="Screenshot 2020-04-29 at 08 40 52" src="https://user-images.githubusercontent.com/66616/80567410-686a2100-89f5-11ea-9ba1-69d73fd0a00a.png">

Inspecting the title element:
<img width="500" alt="Screenshot 2020-04-29 at 08 41 20" src="https://user-images.githubusercontent.com/66616/80567419-6ef89880-89f5-11ea-8750-695f19502401.png">

Url of title starts with `http://` which makes it broken
<img width="500" alt="Screenshot 2020-04-29 at 08 41 32" src="https://user-images.githubusercontent.com/66616/80567442-7750d380-89f5-11ea-8ba0-bafc045d8b21.png">

**Comment by momania** [comment]
Hi,

I noticed the use of `esc_url` in the sources here: 
https://github.com/rupok/essential-addons-for-elementor-lite/blob/master/includes/Elements/Feature_List.php#L790

Reading this about the use of esc_url (https://developer.wordpress.org/reference/functions/esc_url/): 
```
If the URL appears to be an absolute link that does not contain a scheme, prepends http://. ```

This describes the behaviour I have, that an unwanted `http://` is prefixed.
This is also the only place it's used on the link, the one attached to the title. The one on the icon has no `esc_url` applied.
