### ISSUE TITLE
EA Filterable Gallery - Load more button and link crawling issue  

### ISSUE THREAD

**Issue by harish-warrier** [WPDevelopers/essential-addons-for-elementor-lite#480]
Hello,

Below are some of the issues of EA filterable gallery.

1. The 'load more' button in EA filterable gallery has an issue. It needs to be clicked more than 2 times to load the hidden content. Also, when it clicked, the content in other filters also getting loaded.

2. The page links in EA filterable gallery is not crawled by the Google bots and sitemap generator tool some times.

3. This needs more optimizations like the loading time needs to be improved and the frequent bugs after the updates should be fixed.

Hope these issues get resolved as soon as possible. Rest love using the plugin.

**Comment by Fabian570** [comment]
@fabian5701
