### ISSUE TITLE
Error on Filterable Gallery

### ISSUE THREAD

**Issue by xavideva** [WPDevelopers/essential-addons-for-elementor-lite#503]
Hi!
On the Filterable Gallery, when you use an structure "Search and Filter", the Search Bar is displaced (View Image1 attached).

Moreover, at the end of the gallery, the "Load More" button and the following content is displaced too (View Image2 attached).

Moreover, on a Mobile device, is not appearing the text under the images/videos.

Anyone knows how to solve these issues?

Thanks!

Xavier

![Image1](https://user-images.githubusercontent.com/37663093/82742992-03d88280-9d65-11ea-8bef-3b5e018b3642.png)
![Image2](https://user-images.githubusercontent.com/37663093/82742994-076c0980-9d65-11ea-909d-50f5e6872317.png)

**Comment by sabuz** [comment]
Can you please share your site url?
