### ISSUE TITLE
Feature List Bug

### ISSUE THREAD

**Issue by viraax** [WPDevelopers/essential-addons-for-elementor-lite#508]
<img width="1157" alt="Screen Shot 2020-06-07 at 12 44 34 AM" src="https://user-images.githubusercontent.com/14878597/83955167-b5dd7780-a858-11ea-878a-99e239fe4a8d.png">

**Comment by andresvuy** [comment]
Same problem here since the last update, using the free version. And the Accordion also broke the alignment.

**Comment by khan-rafin-ahmed** [comment]
@viraax @andresvuy,

Sorry guys for the trouble. I am checking this now!

**Comment by khan-rafin-ahmed** [comment]
@viraax @andresvuy,

Unfortunately, I couldn't reproduce this issue from our end. Can you guys kindly contact our support team: wpdeveloper.net/support

Mention my name and provide us the template of yours/admin access of your site? 

In the meantime, you could try rollbacking to previous version of EA from here as well: https://essential-addons.com/elementor/docs/faq/roll-back-version-essential-addons/

Thank you!
