### ISSUE TITLE
Essential Addons elementor

### ISSUE THREAD

**Issue by djotheboss** [WPDevelopers/essential-addons-for-elementor-lite#515]
Hello
You have a bug on your advanced tab on your plugin.
My website doesn't work with new update.
Thank you

https://www.mfrbaigneux.com/4eme-3eme/

**Comment by khan-rafin-ahmed** [comment]
@djotheboss,

Hi there,

It seems like caching issue. Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://prnt.sc/r3b588

If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. Thank you.
