### ISSUE TITLE
Page messed up after v 4.0.3 upgrade

### ISSUE THREAD

**Issue by Hombre2014** [WPDevelopers/essential-addons-for-elementor-lite#517]
Hi,

I just upgrade the your plug-in to version 4.0.3 and it messed up my page by moving the text from the right of the icon to the next row. I am sending you screenshot from before and after the upgrade:
Before:

![Before](https://user-images.githubusercontent.com/8495547/84697802-10f52580-af4f-11ea-9b48-511e36021194.PNG)

After:

![After](https://user-images.githubusercontent.com/8495547/84697917-426df100-af4f-11ea-898a-e37a13101d77.PNG)

If you need something else, please, let me know.

Thanks for your time and cooperation.

Regards

**Comment by khan-rafin-ahmed** [comment]
Hi @Hombre2014,

It seems like caching issue. Can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://prnt.sc/r3b588

If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. Thank you.

**Comment by Hombre2014** [comment]
Hi Khan,

 

Thanks for your reply. I checked these and regenerate assets and files, but the problem persist. It is actually in ver. 4.0.2 as well. Version 4.0.1 doesn’t have the problem.

If you need some of the page sources or something else, please, let me know.

 

Regards

**Comment by khan-rafin-ahmed** [comment]
@Hombre2014,

Hey, has your issue been resolved yet? If not, can you please provide us admin access of your site through here: wpdeveloper.net/support

Please provide us the page URL where you are facing this issue as well. Thank you!

**Comment by T0pers** [comment]
Hello! I'm having the same issue as seen in this thread: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/530

**Comment by Hombre2014** [comment]
Hi Khan,

 

Actually version 4.1.0 seems to solve the problem. I tested it and my page looks OK. No icons have been messed up.

 

Regards

Yuriy

**Comment by Hombre2014** [comment]
Hi,

 

I just tested version 4.1.0 and it sees to fix the problem. Did you try it?

 

Regards
