### ISSUE TITLE
PRO - Timeline widget not working after upgrade.

### ISSUE THREAD

**Issue by lmoncany** [WPDevelopers/essential-addons-for-elementor-lite#520]
Hi, The timeline widget is not working since the last upgrade ( 4.0.*) 

Elementor upgraded also.

Support contacted. Tried everything 3 websites with not working timeline (js, responsive)

Solution : Downgrade EA to the 3.6

**Comment by khan-rafin-ahmed** [comment]
@lmoncany,

EA Timeline widget seems fine from our end. Make sure that you have both Free 4.0.3 and PRO 4.0.1 updated on your website. And I assume you have regenerated assets as well from both Elementor and EA Tools, right?

If you have and still facing issue, please provide us the page URL where you are facing this issue and the admin access of your site here: wpdeveloper.net/support

Thank you!
