### ISSUE TITLE
 Essential Addons Settings

### ISSUE THREAD

**Issue by boulette19** [WPDevelopers/essential-addons-for-elementor-lite#524]
Hi, 
in Wordpress, some plugin appear and disappear or sometimes arrows changing in : 

Three Column Carousel
Three Column Carousel

sometimes we can modify or sometimes impossible to modify the block
![Capture d’écran 2020-06-25 à 17 54 59](https://user-images.githubusercontent.com/67430528/85754560-72668280-b70d-11ea-8295-d9abf4121a54.png)
![Capture d’écran 2020-06-25 à 17 54 47](https://user-images.githubusercontent.com/67430528/85754564-72ff1900-b70d-11ea-9df3-305e8a6e6595.png)

is Elementor the concern?
Thanks for your reply and solution

**Comment by sabuz** [comment]
Can you please share url?
