### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by rosertek** [WPDevelopers/essential-addons-for-elementor-lite#526]
´The tiles appear without the normal EA on the top right corner and the icons that represent each tile, when i add them to the layout they don t work properly.

**Comment by abid112** [comment]
Hi rosertek, 

By "tiles" are you indicate this widgets on the Elementor panel?: https://prnt.sc/tfrwq8

Can you please record me reproducing your issue using a tool like this? https://www.loom.com
It helps me to quickly figure out the issue.

Thank you.
