### ISSUE TITLE
Image resize thumbnail

### ISSUE THREAD

**Issue by peggert8** [WPDevelopers/essential-addons-for-elementor-lite#529]
The images in the post slider are being resized 200x300 which makes them very pixilated.

**Comment by abid112** [comment]
Hi @peggert8 ,
I just tested the Post Carousel widget image sizes. On the Layout Setting, The selected size is populated on the post thumbnail successfully: https://prnt.sc/tg9g57
Which Image Size you're using from Layout Setting and what result you get on the the carousel please let me know. 
If you can provide screenshot or page URL, That would be good for better understanding and debugging! Thank you!

**Comment by peggert8** [comment]
Hi. I took a while to find it yesterday. I forgot to text you guys that I solved it. Thank you for your quick reply though

Kind regards Philipp Eggert

________________________________
