### ISSUE TITLE
Filterable Gallery messing with website format and placing (also adding links)

### ISSUE THREAD

**Issue by T0pers** [WPDevelopers/essential-addons-for-elementor-lite#530]
Hello! I am having a problem when using Essetial Addons with the Filterable Gallery.
When the whole plugin is active, below my gallery, some itens and buttons are not in the correct place on the front end, only when editing in Elementor. 
Also, some text that has no link active is link to my page top with the " # " on the end of the page link.
Other problem I saw: One of my image overlays as shown in images 1 vs 2 (Don't know how its called in english elementor) do not appear anymore...
Already updated to version 4.1.0 but the problems still exists. It started alone without updating it.

Also tried to clean cache from my Elementor, Essential Addons and WP SuperCache, including other browsers and computers as suggested on this thread: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/517

 Here are some images showing the problem.

![1](https://user-images.githubusercontent.com/63878963/87712002-6efb6f80-c77e-11ea-823e-f8f9b3e25650.jpg)
![2](https://user-images.githubusercontent.com/63878963/87712003-6f940600-c77e-11ea-97ed-1e431ea16c22.jpg)
![3](https://user-images.githubusercontent.com/63878963/87712005-702c9c80-c77e-11ea-857d-5a7b2f6081ac.jpg)
![4](https://user-images.githubusercontent.com/63878963/87712006-702c9c80-c77e-11ea-81ae-eeb7d2cbdb36.jpg)

My website for closer inspection: https://luisgustavoprod.com/
Thanks!

**Comment by T0pers** [comment]
Hello! Here's an update about this issue: 
Just discovered that those problems only show up when the option "Full Image Clickable" is enabled!
Please check this out, if you need more information please contact me and I will help!

**Comment by abid112** [comment]
Hi @T0pers , I just reproduced your issue. I took the Filterable Gallery with "overlay" layout selected and bellow that I added one of the Elementor Template where some button and section are exists. 
I didn't find any issue that you mentioned. 

Also, As I see your screenshot, There so many blank hyperlink exists in different wrappers which is strange, But when I visited your website I didn't see from the inspect. 

Well the conclusion is, If you still face the problem that you mentioned, Can you please perform the plugin conflict test? The issue you mentioned is so much related for the plugin conflict. I would recommend you to deactivate all the plugins temporary except Elementor and Essential Addons for Elementor. Then check once again. 

Let me know how it goes!

**Comment by T0pers** [comment]
Hello @abid112 
Just made the test again and YES, the problem is still there only wiht Elementor and EAddons activated. 
This do not happen with other elements until now, only when the Gallery option "Full Image Clickable" is selected..
Already tried to remove other Essential Addons elements on the site, but the problem is there only with the Gallery itself.

**Here's a video with the problem itself and my troubleshooting.**
[](https://youtu.be/8xAW3rp0Eeo)

**Comment by khan-rafin-ahmed** [comment]
@T0pers,

Hey, there. Sorry for the inconvenience caused. We had actually fixed that issue last week but it's in the dev version. If you want you can install this dev version from here and test it out: https://github.com/rupok/essential-addons-for-elementor-lite/tree/manzur-dev

Anyways, we are releasing a new version this week which will resolve this issue of yours. Thank you!

**Comment by T0pers** [comment]
Hello! 
Just updated to version 4.1.1 via Wordpress Updates and changed back to the Full Image Clickable, and it look like it's now fixed!
Nothing was messed and the links on other blocks are gone. 
Thank you so much for the time and your help @khan-rafin-ahmed and @abid112
