### ISSUE TITLE
Filterable Gallery not working

### ISSUE THREAD

**Issue by madnomadmedia** [WPDevelopers/essential-addons-for-elementor-lite#531]
I've created filterable controls, enabled them, enabled categories on my gallery items, and used matching names. When I click on a filter control, it doesn't show any gallery items. I tried refreshing my image cache or whatever its called in the settings, which I saw on a support ticket from someone else a while back, but that didn't help. 

Here's a loom showing it

https://www.loom.com/share/0375b012b34c4311b751bb7706e971ae

**Comment by Geogagdi** [comment]
You should place that in control name not in category field
