### ISSUE TITLE
Warning: Illegal string offset 'type' in

### ISSUE THREAD

**Issue by kraeki** [WPDevelopers/essential-addons-for-elementor-lite#532]
Warning all over my website: judogoesorient.ch

![image](https://user-images.githubusercontent.com/1683039/88264891-d78da380-cccc-11ea-8acb-36c6ee2a5ac3.png)

Running php 7.4.

**Comment by khan-rafin-ahmed** [comment]
@kraeki,

Hi there,

First of all, make sure that you are using updated versions of Essential Addons on your website. The current version of Essential Addons Free 4.1.1 and Essential Addons PRO 4.1.0 on your website.

Afterward, make sure to regenerate assets. To do that, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://prnt.sc/r3b588

If you have any third-party caching plugin installed on your website, make sure to purge cache from them. If the issue still persists, please try clearing your browser cache or try another browser too.

If you are not seeing the update of PRO version on your website, you can manually download the latest version by following this documentation: https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/

Let me know how it goes. Thank you.

**Comment by kraeki** [comment]
Hi! Thanks for the support

The problem was that Essential Addons PRO was old (v 3.x). After manually upgrading it like described [here](https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/) it all runs smooth again. 

Best
Andreas
