### ISSUE TITLE
Plugin not working with new update

### ISSUE THREAD

**Issue by Davidholland922** [WPDevelopers/essential-addons-for-elementor-lite#534]
Hi, since I updated some of my plugins a page on my site is not working correctly.
I noticed that when I deactivate the 'Essential Addons for Elementor - pro' version the page does not show at all.

I have reactived it but it is still not showing correctly. here is a link to the page: https://fortus.ie/our-people/

I would really appreciate all the help I can get on this.

Thanks very much in advance.

**Comment by sabuz** [comment]
@Davidholland922 I'm seeing some JS error on the page coming from this script

`jQuery(document).ready(function( $ ){
   setTimeout (function () {
   $( '#rev_slider_1_1' ).find( '.vp-portfolio' ).vpf();
   $( '#rev_slider_1_1' ).find( '.vp-portfolio' ).vpf( 'destroy' );
   console.log('ddddd');
   }, 6000);
   });`

Can you please fix the error and check again? Still if you found problem, Please respond here.

**Comment by khan-rafin-ahmed** [comment]
@Davidholland922,

So has your issue been resolved? Please respond.

**Comment by Davidholland922** [comment]
no i  cannot resolve the issue?  can you provide further instructions??

**Comment by khan-rafin-ahmed** [comment]
@Davidholland922,

Hey, can you please contact support here so that we can have a deeper look: wpdeveloper.net/support

Thank you!
