### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by kellyrenee814** [WPDevelopers/essential-addons-for-elementor-lite#536]
The only thing I am using with the plug is the filterable gallery.

Non-static method WP_Feed_Cache::create() should not be called statically

wp-includes/SimplePie/Registry.php:215
SimplePie_Registry->call()
wp-includes/class-simplepie.php:1313
SimplePie->init()
wp-includes/feed.php:783
fetch_feed()
wp-content/plugins/essential-addons-for-elementor-lite/includes/Classes/WPDeveloper_Dashboard_Widget.php:64
Essential_Addons_Elementor\C\WPDeveloper_Dashboard_Widget->feed()
wp-admin/includes/template.php:1345
do_meta_boxes()
wp-admin/includes/dashboard.php:246
wp_dashboard()
wp-admin/index.php:148

Plugin: essential-addons-for-elementor-lite

**Comment by khan-rafin-ahmed** [comment]
@kellyrenee814,

Can you share a screenshot and the page URL where you are seeing this? Thanks

**Comment by kellyrenee814** [comment]
[image: image.png] I am seeing the error in the query monitor plug-in which
I am using.


Kelly Renée Jerumanis
Travel Advisor / Soul Free Travels
Phone - (512) 348-7622

 info@soulfree-travels.com <info@soulfreetravels.com>
www.soulfreetravels.com
