### ISSUE TITLE
Image HotSpots margin

### ISSUE THREAD

**Issue by GerardPerret** [WPDevelopers/essential-addons-for-elementor-lite#537]
Hi, 
I have a new issue with ImageHotspot Element, it's giving a margin parameter set to auto and a display parameter set to block and this is pushing the image to the right.
If I remove the margin parameter or the display parameter, the image comes back to the right position.

This was not happening with previous versions.

.eael-hot-spot-image img {
    display: block;
    margin: auto;
}

**I am using EA 4.1.2, elementor 2.9.14, pro 2.10.3 and wordpress 5.4.2**

Thank you for your help.

![HotSpot11](https://user-images.githubusercontent.com/42167940/89124815-219b3400-d4da-11ea-823f-e5b4be0e61d8.jpg)
![HotSpot12](https://user-images.githubusercontent.com/42167940/89124816-2233ca80-d4da-11ea-8343-d428cdd2faa1.jpg)

**Comment by abid112** [comment]
Hi there,

I just reproduced your query on my end. I didn't find any issue on my end because of `display: block;` and `margin: auto;`
Anyway, If removing the margin parameter solved your issue, Then you can use this CSS on your stylesheet:

```
.eael-hot-spot-image img {
    margin: unset !important;
}
```

Thanks!

**Comment by GerardPerret** [comment]
Hello,
Thank you for your response, using CSS can make it but from my point of view it's not a very fair solution, better for me to know why I got this issue but I am going to use thing and try to investigate what is causing this problem
Regards.

**Comment by GerardPerret** [comment]
Well I got it, the probleme is coming from the size parameter on the image, I have set this value when creating image hotspots but i think it has been uncorrectly converted with an update.
If i remove the size, the image comes correctly but i have to update each hotspot position!!
Not going to use this parameter anymore!
Regards

![HotSpot13](https://user-images.githubusercontent.com/42167940/89443185-3bde4780-d750-11ea-91d8-52d092470300.jpg)
![HotSpot14](https://user-images.githubusercontent.com/42167940/89443188-3c76de00-d750-11ea-8d31-d5f39111c2d3.jpg)

**Comment by GerardPerret** [comment]
Hi,
   
  
  
   Thank you for your response, please see my comment on github, 
  
  
   I think the size parameter on the image is making something wrong, setting a size on an image is scaling the image but also moving the image out of the margin and this should not happen.
  
  
   Thanks
   
  
  
   Le 5 août 2020 à 12:42, Abid Hasan <notifications@github.com> a écrit : 
   
   
   
   Hi there,
   I just reproduced your query on my end. I didn't find any issue on my end because of display: block; and margin: auto;Anyway, If removing the margin parameter solved your issue, Then you can use this CSS on your stylesheet:
   .eael-hot-spot-image img {
    margin: unset !important;
}

   Thanks!
   —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
    
  
  
    Best Regards/Cordialement 
   Gérard PERRET | GPITS  | Cell + 33 6 08 87 73 06 | gerard.perret@gpits.fr| www.gpits.fr

**Comment by abid112** [comment]
Hi @GerardPerret , I just checked on my end with different Image Size parameters: https://d.pr/i/KSv50N
Anyway, I understand that your previous version defined size is not matched with the current version sizes. We will definitely check this issue more deeply with team.
Thanks for informing us. Cheers!

**Comment by GerardPerret** [comment]
Thank you for this update.
   
  
  
   Le 6 août 2020 à 19:07, Abid Hasan <notifications@github.com> a écrit : 
   
   
   
   Hi @GerardPerret , I just checked on my end with different Image Size parameters: https://d.pr/i/KSv50NAnyway, I understand that your previous version defined size is not matched with the current version sizes. We will definitely check this issue more deeply with team.Thanks for informing us. Cheers!
   —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
    
  
  
    Best Regards/Cordialement 
   Gérard PERRET | GPITS  | Cell + 33 6 08 87 73 06 | gerard.perret@gpits.fr| www.gpits.fr

**Comment by abid112** [comment]
Hi @GerardPerret , 
Hope you're doing well. As we checked your issue deeply in the improved Image Hotspot widget,
So I would recommend you to reposition/update your points in your Image Hotspot widget. I know this is frustrating, But this way you can use the improved  Image Hotspot widget.

Sorry for the inconvenience.

**Comment by GerardPerret** [comment]
Hi, thank you for this update, I have now rebuilt my existing Images.
Few months ago i have reported another issue about ImageHotspots, in tooltip value, if you use a dynamic Tag to get the value from, it doenot work. At this time i got a respons from dev team saying that it should be updated, do you know if this issue has been resolved now?
regards.


![HotSpot15](https://user-images.githubusercontent.com/42167940/91196531-8cffac80-e6fa-11ea-8377-a96c87ea244e.jpg)

**Comment by abid112** [comment]
Hi @GerardPerret , This still not updated yet. But we are working on the ACF integration on the EA Widgets. So basically it will be updated very soon now.

Thanks!

**Comment by GerardPerret** [comment]
Great, thank you
   
  
  
   Le 26 août 2020 à 12:19, Abid Hasan <notifications@github.com> a écrit : 
   
   
   
   Hi @GerardPerret , This still not updated yet. But we are working on the ACF integration on the EA Widgets. So basically it will be updated very soon now.
   Thanks!
   —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
    
  
  
    Best Regards/Cordialement 
   Gérard PERRET | GPITS  | Cell + 33 6 08 87 73 06 | gerard.perret@gpits.fr| www.gpits.fr
