### ISSUE TITLE
SSL Warning after Update to 4.1.2

### ISSUE THREAD

**Issue by alangreenwood** [WPDevelopers/essential-addons-for-elementor-lite#538]
StatusCake is throwing up an error with our site after updating the Essential Addons for Elementor plugin.

"Mixed Content is content that is loaded from insecure sources. To resolve, change the URL on your website to a secure one."
http://www.boardroom-briefings.com/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.js?ver=1596547442

As you can see, the URL appears to be a javascript library for essential addons. Is this something one of our Wordpress admins will have triggered, or is there an issue with the update requesting a http URL when it should be HTTPS?

Thanks, Alan.

**Comment by khan-rafin-ahmed** [comment]
@alangreenwood,

Hi, there. We will fix this in our new update tomorrow. Thank you!

**Comment by alangreenwood** [comment]
Thank you @khan-rafin-ahmed  👍
