### ISSUE TITLE
LIghtbox issue

### ISSUE THREAD

**Issue by vgstef** [WPDevelopers/essential-addons-for-elementor-lite#539]
When I look and the Wordpress debug info, I get those Notice: 

Notice: Trying to access array offset on value of type null in /wp-content/plugins/essential-addons-elementor/includes/Elements/Lightbox.php on line 1574

Notice: Trying to access array offset on value of type null in /wp-content/plugins/essential-addons-elementor/includes/Elements/Lightbox.php on line 1575

Notice: Trying to access array offset on value of type null in /wp-content/plugins/essential-addons-elementor/includes/Elements/Lightbox.php on line 1582

Can you fix that?

Thanks

**Comment by abid112** [comment]
Hi @vgstef ,

I just tested on my end with 3 different PHP versions (5.6, 7.3, 7.4)
This issue comes up in PHP 7.4. Other 2 version is seems fine. 

Thanks for informing us. We will definitely look over this.
