### ISSUE TITLE
Typeform connection

### ISSUE THREAD

**Issue by schoolhouseagency** [WPDevelopers/essential-addons-for-elementor-lite#542]
Can't connect to typeform. After clicking "Get Access". I login and the popup closes without asking for the typeform token, after trying again, it asks me to confirm that this is my account, upon confirmation the popup closes again.

**Comment by abid112** [comment]
Hi @schoolhouseagency ,

Make sure you're using the live URL with SSL enabled. 
This TypeForm connection not working when you tried in localhost. 

Let me know, Thanks!
