### ISSUE TITLE
failed to open stream: Permission denied

### ISSUE THREAD

**Issue by shiianjun** [WPDevelopers/essential-addons-for-elementor-lite#544]
Warning: file_put_contents(/usr/share/nginx/html/blog/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.css): failed to open stream: Permission denied in /usr/share/nginx/html/blog/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 274

Notice: Trying to access array offset on value of type null in /usr/share/nginx/html/blog/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1449

Notice: Trying to access array offset on value of type null in /usr/share/nginx/html/blog/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1451

Warning: file_put_contents(/usr/share/nginx/html/blog/wp-content/uploads/elementor/css/post-140.css): failed to open stream: Permission denied in /usr/share/nginx/html/blog/wp-content/plugins/elementor/core/files/base.php on line 180

**Comment by abid112** [comment]
Hi @shiianjun ,

As per as your error message, I can see it says **Permission denied** , So, can you please go to your FTP server or cPanel and change the File permission of the /wp-content folder to '755' **recursively**.
  
Also make sure that you're using latest version of Essential Addons for Elementor Free(4.2.0) and Pro(4.12) as this /Traits/Generator.php issue mostly happen for the version mismatch.

Let me know how it goes!
Thanks!

**Comment by shiianjun** [comment]
/**
 * Plugin Name: Essential Addons for Elementor
 * Description: The Essential plugin you install after Elementor! 70+ Premium elements, including WooCommerce, Event Calender, Data Table, Post Grid, Instagram Feed.
 * Plugin URI: https://essential-addons.com/elementor/
 * Author: WPDeveloper
 * Version: 4.1.1
 * Author URI: https://wpdeveloper.net/
 * Text Domain: essential-addons-for-elementor-lite
 * Domain Path: /languages
 *
 * WC tested up to: 4.1.0
 */

**Comment by shiianjun** [comment]
1  sudo find /usr/share/nginx/html/blog -type d -exec chmod 755 {} \; sudo find /usr/share/nginx/html/blog -type f -exec chmod 644 {} \;
2   Essential Addons for Elementor:  Version: 4.1.1 --> Version 4.2.0 

the problem is still .

**Comment by shiianjun** [comment]
the list files iexisted,
-rw-r--r--. 1 nginx nginx  38316 8月  16 17:48 cb70d11b8.min.css
-rw-r--r--. 1 nginx nginx  47896 8月  16 17:48 cb70d11b8.min.js

but, elementor or addon  don't operate the two files.

**Comment by shiianjun** [comment]
2020/08/17 00:00:42 [error] 107881#107881: *285 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/usr/share/nginx/html/blog/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.css): failed to open stream: Permission denied in /usr/share/nginx/html/blog/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 274PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/nginx/html/blog/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1449PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/nginx/html/blog/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1451" while reading response header from upstream, client: 192.168.3.120, server: blog.home.edu, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "blog.home.edu"
2020/08/17 00:00:42 [error] 107881#107881: *285 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/usr/share/nginx/html/blog/wp-content/uploads/essential-addons-elementor/cb70d11b8.min.js): failed to open stream: Permission denied in /usr/share/nginx/html/blog/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 274" while reading upstream, client: 192.168.3.120, server: blog.home.edu, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "blog.home.edu"

**Comment by khan-rafin-ahmed** [comment]
@shiianjun,

Have you tried regenearting assets from Elementor and EA Tools? If so and still facing issue, please contact us here and provide us admin access: wpdeveloper.net/support

Thank you!
