### ISSUE TITLE
Bug Issue 

### ISSUE THREAD

**Issue by Katlijn09** [WPDevelopers/essential-addons-for-elementor-lite#547]
![Image 2020-08-30 at 3 48 50 PM](https://user-images.githubusercontent.com/70483432/91665301-dda94800-eaf4-11ea-9dcc-0f4963855454.png)
![Image 2020-08-30 at 4 45 26 PM](https://user-images.githubusercontent.com/70483432/91665302-deda7500-eaf4-11ea-95d2-beb67f57703c.png)
![Image 2020-08-30 at 3 47 09 PM](https://user-images.githubusercontent.com/70483432/91665344-37117700-eaf5-11ea-877a-276051c060cd.png)

I don't know how to fix this, and I'm not a professional 
I hope you can help me.

Kind Regards 
Kate

**Comment by rupok** [comment]
Hey @Katlijn09 

Can you post the full error messages? Meantime can you confirm you are using latest version of Essential Addons?

**Comment by Katlijn09** [comment]
Hi, 
yes 

I add video with the steps I make till the error.  Don’t hesitate to ask more information. Kind Regards





Founder of Urban de Luxe by Kate
www.urbandeluxebykate.com
Contact: urbandeluxe.bykate@gmail.com

**Comment by rupok** [comment]
Hi Kate,

Can't see the video attached in your reply. Can you paste it again?

**Comment by Katlijn09** [comment]
Hi, 

https://share.getcloudapp.com/4gu94mNW <https://share.getcloudapp.com/4gu94mNW>

Founder of Urban de Luxe by Kate
www.urbandeluxebykate.com
Contact: urbandeluxe.bykate@gmail.com

**Comment by rupok** [comment]
Okay, I see you are up to date. Can you please paste the full error message as seen here 
https://user-images.githubusercontent.com/70483432/91665302-deda7500-eaf4-11ea-95d2-beb67f57703c.png

**Comment by Katlijn09** [comment]
hi,


Founder of Urban de Luxe by Kate
www.urbandeluxebykate.com
Contact: urbandeluxe.bykate@gmail.com

**Comment by rupok** [comment]
Your reply is the missing attachment again.
