### ISSUE TITLE
Buggy Post Grid 

### ISSUE THREAD

**Issue by vivaciousvipin** [WPDevelopers/essential-addons-for-elementor-lite#548]
The post grid on the latest version (4.2.3) seems to be buggy. Have a look:

The blue color shows the bug.
The red color shows what is supposed to happen (the read more button is collapsing - on desktop as well as mobile, my site is misfitwanderers.com).

![image](https://user-images.githubusercontent.com/37480251/92254650-d4eab480-eeee-11ea-8958-1bb8bad82af1.png)

**Comment by abid112** [comment]
Hi there,

I went through your website and found this ok on my end.
Have a look:

Desktop: https://d.pr/i/OiBKtS
Mobile: https://d.pr/i/hXx10M

Is this issue fixed on your end? Please let me know, Thanks!

**Comment by vivaciousvipin** [comment]
> Hi there,
> 
> I went through your website and found this ok on my end.
> Have a look:
> 
> Desktop: https://d.pr/i/OiBKtS
> Mobile: https://d.pr/i/hXx10M
> 
> Is this issue fixed on your end? Please let me know, Thanks!

Yes, it is fixed. Apparently I had to delete the block and create it all the way back from scratch with all the customizations. Other options didn't work!

Thanks though, for checking. 👍
