### ISSUE TITLE
Checkout addon bug 

### ISSUE THREAD

**Issue by dun981** [WPDevelopers/essential-addons-for-elementor-lite#550]
Hi I am trying to add a Checkout, addon on my Page. And it seems there is a bug here. What is happening is 
when i drag the addon into the page the addon does not open at all.Please find a photo to see what i mean 
![screenshot-2020-09-13-at-07440_6076ky](https://user-images.githubusercontent.com/63806650/93011486-ec810780-f596-11ea-8c01-871600db4d3a.png)

**Comment by khan-rafin-ahmed** [comment]
@dun981,

To use EA Woo Checkout, you will need to replace the default Checkout page with another page of yours. If you want, you can even create a new page and assign it as WooCommerce Checkout page. Screenshot: https://d.pr/i/885NGr

Also, make sure to add products in your cart before you try to edit your checkout page with Elementor.

It should be working fine afterward. For more info, check out this doc: https://essential-addons.com/elementor/docs/woo-checkout/

Thank you!

**Comment by dun981** [comment]
That is a new page.But yes the cart was empty so i will try to add products to the chart and try again
