### ISSUE TITLE
BUG: "Controls_Manager::add_control_to_stack" Error Recorded in WordPress WP_DEBUG Log

### ISSUE THREAD

**Issue by tictag** [WPDevelopers/essential-addons-for-elementor-lite#551]
[Essential Addons for Elementor - Pro  v4.1.6]

**Overview**

There is a bug in v4.1.6 where when the pro plugin is activated the following error is recorded in WordPress WP_DEBUG log every time the Elementor workspace is loaded:

`[20-Sep-2020 00:36:31 UTC] PHP Notice:  Elementor\Controls_Manager::add_control_to_stack was called <strong>incorrectly</strong>. Cannot redeclare control with same name "title_tag". Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 1.0.0.) in /home/customer/www/new.ksa-uk.net/public_html/wp-includes/functions.php on line 5225`

**Steps To Recreate**

(1) Install Lite and Pro Addons
(2) Enter Elementor workspace e.g. Edit With Elementor
(3) Check WP_DEBUG, note error above

Note: When all elements are disabled in settings, the error is not recorded.

See here for a detailed step-by-step video screencast of this issue: https://1drv.ms/v/s!AiwD9-8HyNC59RliWK5NLrOaFlQU?e=dAOoiv

**System**

PHP v7.3.20
WordPress v5.5.1
Essential Addons for Elementor v4.2.4
Essential Addons for Elementor - Pro  v4.1.6

**Further Info**

This issue *may* be related to an issue where PHP hangs after consuming more memory than is allocated, causing the site to go down and report HTTP 500 to all requests.

I hope this helps.

Regards,
David.

**Comment by abid112** [comment]
Hi @tictag ,

As I can see from our support channel, You already informed that our dev team is already aware about this and this will be fixed on the next version of Essential Addons for Elementor Pro.

Thanks for the details report. We really appreciate your effort.

Thanks!

**Comment by tictag** [comment]
Apologies, I did check the other issues for a duplicate but didn't notice it. Please feel free to either merge this with the other issue, or close.

And you are welcome. I see bug reporting as a 'spend-to-save' thing ... the more effort I put in to detail, the faster it will be fixed!! ;-)
