### ISSUE TITLE
Advanced Tabs having issue with loading Image carousel

### ISSUE THREAD

**Issue by sudo8-com** [WPDevelopers/essential-addons-for-elementor-lite#555]
Wordpress 5.5.1
Elementor Pro: 3.0.5 
Essential Addon Pro:  4.1.6
Theme: Jacqueline 1.6.3

I have advanced tabs loading from elementor templates. On Tab 1, everything works. But on tab 2 and onwards it has trouble loading image carousel and other media files on desktop.

https://noelbeauty.pro/our-service   (tab 3)

Thanks!

**Comment by abid112** [comment]
Hi @sudo8-com ,

Currently in Essential Addons for Elementor - Advanced Tab widget, If any JS elements(ie. image carousel) exists from the second tab, That doesn't work unfortunately from that second tab.
Our dev team already aware of this issue and they're trying to fix.

Thanks!

**Comment by abid112** [comment]
Hi @sudo8-com ,

Currently in Essential Addons for Elementor - Advanced Tab widget, If any JS elements(ie. image carousel) exists from the second tab, That doesn't work unfortunately from that second tab.
We already aware of this issue and trying to fix this as soon as possible.

Thanks!
