### ISSUE TITLE
Twitter feed has stopped working

### ISSUE THREAD

**Issue by fernando-partridge** [WPDevelopers/essential-addons-for-elementor-lite#559]
Tweets don't load since most recent update (4.3.1)

**Comment by abid112** [comment]
Hi @fernando-partridge ,

Thanks for reaching out to us. We already aware about this issue. This Twitter Feed issue will be fixed soon with the new update of Essential Addons for Elementor.

**Comment by abid112** [comment]
Hi @fernando-partridge ,

We just released a new version of Essential Addons for Elementor **4.3.2** where we fixed the Twitter Feed issue that you're facing.
So please update your plugin to version **4.3.2** and then check back.

Let me know how it goes
Thank you.
