### ISSUE TITLE
White Screen of death

### ISSUE THREAD

**Issue by gapaloupos** [WPDevelopers/essential-addons-for-elementor-lite#560]
Hello,

When i activate the Essential Addons for Elementor - Pro plug in, my site goes blank (white screen of death).
When I deactivate it, everything is normal again...
What should I do?

**Comment by abid112** [comment]
Hi @gapaloupos ,

Are you using any caching plugin on your website? Can you please try purging cache from your Caching tool and check back? Also you can deactivate the caching plugin and check back aswell.

Besides that, We're planning to release a new update as soon as possible where this asset related issue will be gone I believe.

Thanks!

**Comment by abid112** [comment]
Hi @gapaloupos  ,

We just released a new version of Essential Addons for Elementor **4.3.2** where we fixed the asset related issues.
So please update the plugin to version **4.3.2** and after that regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘Tools’ tab and hit the **‘Regenerate Assets’** button. Check out this screenshot: https://prnt.sc/pvozsx

Also, Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://prnt.sc/r3b588

Hope your issue will be resolved
Let me know how it goes. Thank you.
