### ISSUE TITLE
tooltip plugin - link forced to open in a new tab

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#561]
i wold like it to open in the same tab but even if there's no tick on "Link Option/Open in a new tab" it open in a new tab anyway

**Comment by abid112** [comment]
Hi @Azertooth ,

We already aware about this issue. This will be fixed in the future version of Essential Addons for Elementor.

Thanks for pointing this. We really appreciate it.
