### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method

### ISSUE THREAD

**Issue by ColoreeGraphiste** [WPDevelopers/essential-addons-for-elementor-lite#562]
Hello,

Today I have a problem on this website https://mongeard;fr

On the home page, this error message appears when I want to use the ELEMENTOR editor 👍 

"Fatal error: Uncaught Error: Call to undefined method Essential_Addons_Elementor\Pro\Elements\Post_Carousel::get_template_list_for_dropdown() in /home/montjumy/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php:404 Stack trace: #0 /home/montjumy/public_html/wp-includes/class-wp-hook.php(287): Essential_Addons_Elementor\Classes\Bootstrap->layout(Object(Essential_Addons_Elementor\Pro\Elements\Post_Carousel)) #1 /home/montjumy/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/montjumy/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/montjumy/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Helper.php(150): do_action('eael/controls/l...', Object(Essential_Addons_Elementor\Pro\Elements\Post_Carousel)) #4 /home/montjumy/public_html/wp-content/plugins/essential-addons-elementor/includes/Elements/Post_Carousel.php(74): Essential_Addons_Elementor\Pro\Elements\Post_Carousel->eael_layout_ in /home/montjumy/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php on line 404
une erreur critique est survenue sur votre site."

Can you help me please ?
Thanks !

**Comment by sabuz** [comment]
Hi!
Can you please make sure that you're using latest version of EAEL?

**Comment by khan-rafin-ahmed** [comment]
Hi @ColoreeGraphiste,

Please make sure that you are using updated versions of Essential Addons on your website. The current version of Essential Addons Free **4.3.3** and Essential Addons PRO **4.2.1** on your website.

If you are not seeing automatic update of PRO plugin, please follow this doc: https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/

Your issue should be resolved. Thank you!
