### ISSUE TITLE
Illegal string offset 'file' in t/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 320

### ISSUE THREAD

**Issue by Sisko212** [WPDevelopers/essential-addons-for-elementor-lite#566]
Without any changes to the site, elementor started returning this error:

Warning: Illegal string offset 'file' in ..../wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 320
Warning: Illegal string offset 'type' in ..../wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 320

PHP Fatal error: Uncaught Error: Call to
undefined method
Essential_Addons_Elementor\Pro\Elements\Content_Timeline::get_template_list_for_dropdown()
in ..../wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php:404
Stack trace:
#0 .../wp-includes/class-wp-hook.php(287): Essential_Addons_Elementor\Classes\Bootstrap::layout()
#1 .../wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 ..../wp-includes/plugin.php(478): WP_Hook->do_action()
#3 ..../wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Helper.php(150): do_action()
#4 ..../wp-content/plugins/essential-addons-elementor/includes/Elements/Content_Timeline.php(224): Essential_Addons_Elementor\Pro\Elements\Content_Timeline->eael_layout_controls()
#5 ..../wp-content/plugins/elementor/includes/base/controls-stack.php(1929): Essential_Addons_Elementor\Pro\Elements\Content_Time in ...../wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php

And take the whole site offline
If I completely disable Essentials Addos for Elementor-Pro, the site still works, but obviously I don't have some pieces anymore
Do you have suggestion where to look to fix the error ?

**Comment by abid112** [comment]
Hi @Sisko212 ,

From your error message, I can see that you're using both Essential Addons for Elementor Free and Pro. This error general happen when the Essential Addons for Elementor Free is not match with the latest version of Essential Addons for Elementor Pro.

So please make sure that you're using latest version of Essential Addons for Elementor Free(**4.3.3**) and Pro(**4.2.1**).

If you are not seeing the update of PRO version on your website, you can manually download the latest version by following this documentation: https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/

Thanks!

**Comment by Sisko212** [comment]
Hi abid112,
Thanks for your help... look wo works, in fact my version of Essentials Addons Pro was misaligned with the free version.
Just a question then... Essentials Addons Pro, could works without Essentials Addons Free ?
Thanks.

**Comment by khan-rafin-ahmed** [comment]
@Sisko212,

You need both Free and PRO version of EA. Thank you!
