### ISSUE TITLE
Fancy text 

### ISSUE THREAD

**Issue by 360tur** [WPDevelopers/essential-addons-for-elementor-lite#567]
I have made a website. [](https://360tur.se/en/ ) using Elementor and putting Essential addons Fancy text on the page. However it is very sporadic whether it works or not. The cursor does not show though it is checked to show. The moving text works sometimes but not all the time.

**Comment by khan-rafin-ahmed** [comment]
@360tur,

Hi, there. Please share your page URL here so that we can check what's happening.

Thank you!

**Comment by 360tur** [comment]
Hej
https://360tur.se/en/
