### ISSUE TITLE
calendrier

### ISSUE THREAD

**Issue by ferreiratof** [WPDevelopers/essential-addons-for-elementor-lite#568]
Bug avec le calendrier. 
Lorsque l'on insère le widget calendrier sur une page on ne peux plus ajouter d'autres widgets. Ce bug apparait sur plusieurs de mes sites.
en supprimant le widget calendrier tout fonctionne normalement

**Comment by khan-rafin-ahmed** [comment]
Hi @ferreiratof,,

Please check for plugin conflicts by disabling all the plugins except for Elementor & Essential Addons & check back.

Let me know how it goes. Thank you!

**Comment by ferreiratof** [comment]
bonjour
il s'agit bien d'un conflit avec happy addons élémentor. Lorsqu'il est désactivé cela fonctionne. cordialement
 
 
 
 
> Message du 04/11/20 11:24> De : "khan-rafin-ahmed" > A : "WPDevelopers/essential-addons-for-elementor-lite" > Copie à : "ferreiratof" , "Mention" > Objet : Re: [WPDevelopers/essential-addons-for-elementor-lite] calendrier (#568)> >
>
> Hi @ferreiratof,,
> Please check for plugin conflicts by disabling all the plugins except for Elementor & Essential Addons & check back.
> Let me know how it goes. Thank you!
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/568#issuecomment-721646413", "url": "https://github.com/WPDevelopers/essential-addons-for-elementor-lite/issues/568#issuecomment-721646413", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
