### ISSUE TITLE
Can't edit elementor editor due to this plugin's issue.

### ISSUE THREAD

**Issue by villanueva123** [WPDevelopers/essential-addons-for-elementor-lite#570]
I got this issue Illegal string offset 'file' in /home/creat463/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Generator.php on line 320

**Comment by abid112** [comment]
Hi @villanueva123 ,

Sorry for the late response. Make sure that you're using the latest version of Essential Addons for Elementor Free(**4.3.7**) and Pro(**4.2.3**). This issue is happening when both EA Free and Pro are not up to date.

Hope you understand.
Thanks!
