### ISSUE TITLE
There has been a critical error on your website.

### ISSUE THREAD

**Issue by sushilbalami** [WPDevelopers/essential-addons-for-elementor-lite#572]
Uncaught Error: Call to undefined method Essential_Addons_Elementor\Pro
\Elements\Content_Timeline::get_template_list_for_dropdown() in /home/mysite/dev.mysitege.edu.np/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php:404 Stack trace: #0 /home/mysite/dev.mysitege.edu.np/wp-includes/class-wp-hook.php(287): Essential_Addons_Elementor\Classes\Bootstrap::layout(Object(Essential_Addons_Elementor\Pro\Elements\Content_Timeline)) #1 /home/mysite/dev.mysitege.edu.np/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #2 /home/mysite/dev.mysitege.edu.np/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/mysite/dev.mysitege.edu.np/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Helper.php(153): do_action('eael/controls/l...', Object(Essential_Addons_Elementor\Pro\Elements\Content_Timeline)) #4 /home/mysite/dev.mysitege.edu.np/wp-content/plugins/essential-addons-elementor/includes/Elements/Content_Timeline.php( in /home/mysite/dev.mysitege.edu.np/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Controls.php on line 404

There has been a critical error on your website.

**Comment by sabuz** [comment]
@sushilbalami Can you please make sure that you're using latest version of EA for both lite and pro?

**Comment by aidas-emersoft** [comment]
Same issue here. Site breaks with the following plugin versions:

Elementor: 3.0.13
Essential Addons for Elementor - Pro: 3.3.1
Essential Addons for Elementor: 4.3.6

I've switched to v4.3.0 Essential Addons for Elementor to mitigate the problem.

**Comment by abid112** [comment]
Hi @aidas-emersoft , 

Latest version of Essential Addons for Elementor Pro is **4.2.2**
So please update your EA Pro plugin to the latest one. Hopefully your issue will be resolved.

If you are not seeing the update of PRO version on your website, you can manually download the latest version by following this documentation: https://essential-addons.com/elementor/docs/manually-update-essential-addons-pro/

Let me know how it goes. Thank you.
