### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by studiohsi** [WPDevelopers/essential-addons-for-elementor-lite#573]
Hi there, 

after the last update to v. 4.3.6 of Essential Addons for Elementor Lite I get an error of "Failed to load resource: the server responded with a status of 500". If I turn off the plugin, the issue disappears and the site renders content without any issues.

The site's URL is "top-potovanja.si" and is built on OceanWP Lite theme and Elementor builder. What is special about my setup is that it is a multisite WP installation.

In addition to described, I am having multiple sites using your plugin on another provider's account, where I haven't updated to the latest version yet, and everything works without any issues there. Can you please have a look what may went wrong with the last update of the plugin? 

If you need any other support from me, please let me know.

Thanks and best!

**Comment by abid112** [comment]
Hi @studiohsi ,

That's strange!
Can you please create a support ticket with temporary admin access and the FTP access of your website from here: https://wpdeveloper.net/support/new-ticket/

Our Technical Support Team will get back to you there and try to resolve this issue as soon as possible.
Thanks!
