### ISSUE TITLE
Keep getting a blank white screen when I activate this plug in

### ISSUE THREAD

**Issue by poonamhalai123** [WPDevelopers/essential-addons-for-elementor-lite#575]
I'm using OceamWP theme, and this plug in seems to have a bug. When I activate it, whenever I go to my website and click on a blog post, it becomes a blank white screen. Not sure why. It's definitely this plug in, because when its deactivated this error seems to go away

**Comment by khan-rafin-ahmed** [comment]
@poonamhalai123,

We have fixed this issue with our new update today. Please check and update your plugin to the latest versions.

Thank you!
