### ISSUE TITLE
Post Carousel Suddenly Doesn't Work As Intended

### ISSUE THREAD

**Issue by LeahKeys9** [WPDevelopers/essential-addons-for-elementor-lite#576]
Hi all, 
I'm a pro member but I believe this issue occurs on an element included with the free package. The post carousel looks fine while editing the page,  but when I view the page, it does not showcase multiple posts or show the applied animation.

![carousel working](https://user-images.githubusercontent.com/74842534/99890965-9b863300-2c19-11eb-894a-766e6249c73e.PNG)
^^how it should look ^^

![carousel not working](https://user-images.githubusercontent.com/74842534/99890961-9628e880-2c19-11eb-8085-ea9c63ea8aca.PNG)
^^how it actually looks^^

I added images to show what I mean, but I haven't been able to find help much online. From what I can tell, I just started noticing this issue today.

**Comment by abid112** [comment]
Hi @LeahKeys9 

I just tested on my end and it seems fine on my end.
Can you please try doing regenerate assets from **wp-admin -> Essential Addons** then, switch to the **‘Tools’** tab and hit the **‘Regenerate Assets’** button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://prnt.sc/r3b588 

If the issue still persists, Can you please give me your page URL so that I can check on my end.

Let me know how it goes. Thank you.

**Comment by LeahKeys9** [comment]
hi @abid112 
I really appreciate the help! It still did not work for me after regenerating the files. I won't be able to share a link with you only because I don't want to be using a broken function on my live website (I hope you can understand). I was hoping the attached image would suffice since it captures the problem entirely. That image does not move and will not move if the user clicks on the side arrows that pop up when they hover over it.

If it works fine on your end then perhaps I have a conflict I need to look into.

Thank you!

**Comment by sohailahmad49** [comment]
I have the same But the difference this the slider is working fine on tablet mode and not working in desktop mode plus my mobile slides of control by tablet mode so the number of slides i  have in a tablet made that is also the number of slide in mobile mode
so the mobile version is also not working correctly

**Comment by sohailahmad49** [comment]
HI
So in My Case, It was conflicting with another plugin so it's working now 
Conflicting Plugin Name: **HT Mega - Absolute Addons for Elementor Page Builder**
Disable That Plugin And It should Work Fine

**Comment by JonasN78** [comment]
So this issue looks not to be resolved. I have the same issue as above. Post Carousel worked for maybe a week. I needed to turn it into a template to synchronize on multiple pages. When I added the template to a page, the carousel broke on all pages simultaneously. It works in mobile mode on all pages, but fails to slide on tablet or desktop mode. 

My add-ons consists of Elementor 3.11.2, Essential Addons 5.6.0, WP Forms 7 5.7.4, and Smart Slider 3 3.5.1.14. With all turned off except Elementor and EA, the slider fails to slide. I have tried different themes (default 2021, 2022 & 2023), but same issue on all. As mentioned above, I regenerated the Elementor assets/files which made no change to the slider's functionality. I tried removing the template files, every instance of the template and the original carousel that the template was made from, then tried building the carousel again - still no slide function on anything but mobile.

Site is not public as its a migration from Umbuco to Wordpress. Current site needs to remain in place until migration is complete and approved.

**Comment by abid112** [comment]
Glad to know that it's working now @JonasN78 
Thanks for letting us know.

**Comment by hatanasova** [comment]
I am having the exact same issue. I tried deactivating all elementor-related plugins and activating them all back again. I also tried regenerating assets and rolling back to a previous plugin version. The issue is still there and the carousel does not work at all.
