### ISSUE TITLE
Protected Content Not Working Properly (Bug?)

### ISSUE THREAD

**Issue by InviteJapan** [WPDevelopers/essential-addons-for-elementor-lite#580]
Hi,

We are currently facing a serious problem or bug with your plugin/widget. 
The problem about the widget is when we insert the correct password it wont show the protected content and take us back to it normal insert password page, so after that when we refresh, type in wrong answer or just by clicking submit button without any answer the protected content will shows. So, basically the content was loaded and the widget is not showing it. 

Can the team look into this and update the plugin so we can continue on our work?

Regards,
Kazu

**Comment by InviteJapan** [comment]
Here is the link where you can see the bug.
https://drive.google.com/file/d/1yn9dzPle75paZr8paWOQKbqRPw5mAjhb/view?usp=sharing

**Comment by khan-rafin-ahmed** [comment]
@InviteJapan,

Hi, there. We have fixed this with the new update. Please check and let me know.

Thank you!
