### ISSUE TITLE
Custom JS Issue on Pages and Templates

### ISSUE THREAD

**Issue by jaysauce** [WPDevelopers/essential-addons-for-elementor-lite#582]
Whenever I save custom JS to a page or theme builder, I am able to load the custom JS once I've saved it. But subsequent refreshes of the page cause the JS not to work. I've tried regenerating the assets, as well as setting the JS to be embedded on the page instead of in an external file with 0 luck.

I've inspected the source and did see the JS I added on the page on initial load. But once I refreshed, the JS just magically disappears.

Here are the exact steps to reproduce:

1. Add some JS code to the custom JS area on a page.
2. Click Update in elementor.
3. Go to the page in another tab and the JS works.
4. Refresh the page and the JS disappears and no longer works.

**Comment by abid112** [comment]
Hi @jaysauce ,

Thanks for pointing this out.
Our dev team is investigating this issue on our end. Hopefully, this will be fixed in the future update of Essential Addons for Elementor.

Thanks!

**Comment by abid112** [comment]
Hi @jaysauce ,

We fixed this issue on the dev branch. Please pull/download this "dev" branch: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/dev

Note that, This dev branch will be live in the future version of Essential Addons for Elementor

Let me know how it goes.
Thanks!
