### ISSUE TITLE
image broke site

### ISSUE THREAD

**Issue by joyzsmith** [WPDevelopers/essential-addons-for-elementor-lite#583]
dear developer 
I am using this elementor addons plugins in my site, this post grid feature is awesome but I can't resize these images into height=200px, widht=200px there is no option in inspect, and many cache plugin like w3 cache, hummingbird broke this CSS, JS
Please fix this troubleshoot, how I fix this. Have a nice day

**Comment by abid112** [comment]
Hi @joyzsmith ,

Hope you're doing good.
You can define your Image Size from the Layout Settings of EA Post Grid widget: https://d.pr/v/4wYzFd

Also for the caching plugins, Can you please tell me which settings you're using currently? If you have HTML Minify option turned on, You can temporarily disable this setting from your caching plugin and let me know how it goes.

For further investigation, Please create a support ticket here: https://wpdeveloper.net/support/new-ticket/

We will check back and get back to you there.
Thanks!

**Comment by joyzsmith** [comment]
many Cache plugins like W3 cache, hummingbird, Autoptimize are broke my
Post Grid Layout. Without the cache plugin, I can't do anything in SEO or
Ranking with 250-400ms blocking time. Please tell me what can I do. Thanks
for replying
[image: Screenshot_2020-12-13-20-21-06-49.jpg]
