### ISSUE TITLE
element essential addons not working in my site

### ISSUE THREAD

**Issue by DEEVAAANSHI** [WPDevelopers/essential-addons-for-elementor-lite#584]

**Comment by DEEVAAANSHI** [comment]
#573

**Comment by stefanimerritt** [comment]
The same is happening to me. Did you get a response or find out how to fix it?

**Comment by FariaAarin** [comment]
Hi @DEEVAAANSHI,

Sorry for the inconvenience caused. Can you please create a support ticket with temporary admin access and the FTP access of your website from here: https://wpdeveloper.net/support/new-ticket/

Our Technical Support Team will get back to you there and try to resolve this issue as soon as possible.
Thanks!
