### ISSUE TITLE
Showing Invalid Username msg for Invalid Password

### ISSUE THREAD

**Issue by hassanwebx** [WPDevelopers/essential-addons-for-elementor-lite#585]
Hello,

We made a login/registration form for our client and on testing, we found that when we are entering an incorrect password for an already existing user it is showing the Invalid username validation message instead of the Invalid password validation message.
( See Screenshot: https://prnt.sc/w3xh2a )

We have double-checked on the Elementor edit the validation messages and for the Invalid Password, the validation message is set correctly. It is just showing an Invalid username validation message instead.

**Comment by abid112** [comment]
Hi @hassanwebx ,

Thanks for pointing this out. We really appreciate it. We will fix this in the future version of Essential Addons for Elemmentor.

Cheers!
