### ISSUE TITLE
Can you please make 'Read more' String in Twitter Feed translatable?

### ISSUE THREAD

**Issue by itrich** [WPDevelopers/essential-addons-for-elementor-lite#586]
The "Read More" string under each Twitter post is not translatable. Can you please merge my Pull Request #463 into your main branch? I have to manually edit your plugin after each update, which is pretty annoying...!

**Comment by abid112** [comment]
Hi @itrich ,

Hope you're doing good.
Thanks for pointing this out. We're planning to add a **Read More** string controller from the Elementor panel. This will be available in the future version of Essential Addons for Elementor.

Cheers!

**Comment by abid112** [comment]
Hi @itrich , 

We've added "Read More" string controller in one of our updates: https://d.pr/i/srQzPc
Please make sure to update Essential Addons for Elementor plugin to get this feature.

Cheers!
