### ISSUE TITLE
New update issue !!

### ISSUE THREAD

**Issue by MuhammadTawfeeq** [WPDevelopers/essential-addons-for-elementor-lite#587]
After updating the plugin it causes my site to keep refreshing on the same page !!

https://outstandingmasters.com/mastersser

**Comment by abid112** [comment]
Hi @MuhammadTawfeeq ,

That's strange! 
Can you please create a support ticket here: https://wpdeveloper.net/support/new-ticket/

We will check and get back to you there don't worry.
Thanks!
