### ISSUE TITLE
EA login widget in an Elementor popup – generates error after successful login

### ISSUE THREAD

**Issue by Xuqian-Yan** [WPDevelopers/essential-addons-for-elementor-lite#589]
On the [WordPress Forum](https://wordpress.org/support/topic/ea-login-widget-in-an-elementor-popup-generates-error-after-successful-login/), the following problem has been encountered by three users, so I thought maybe we can get a quick solution by re-posting it on Github. 

> After login through this popup, the broswer stays at the same URL as the one where the popup was invoked, but instead of showing that page, it displays the error message: 
"This page doesn’t seem to exist.
It looks like the link pointing here was faulty. Maybe try searching?”

For more descriptions of the issue and a preliminary solution please refer to the [Forum](https://wordpress.org/support/topic/ea-login-widget-in-an-elementor-popup-generates-error-after-successful-login/).

Thank you very much!

**Comment by kamalahmed** [comment]
Hi, this issue is fixed already. It is in the queue for release SOON. Thank you very much for your patience.
