### ISSUE TITLE
WooCommerce Product Grid AddOn doesn't use internationalized string for "Sale!"

### ISSUE THREAD

**Issue by stronganchor** [WPDevelopers/essential-addons-for-elementor-lite#590]
When using the Product Grid element, it automatically pulls the default WooCommerce string for the "Add to Cart" button, and there is an option to change the text for the "load more" button, but for products that are on sale, it doesn't use the translated string in the translated version of WooCommerce and I didn't see an easy way to customize the string in the interface.

Could this either be fixed so it uses the translated string instead of "SALE!" or could an option be added that allows you to customize this string (like what was done for the "load more" button)?

![image](https://user-images.githubusercontent.com/77190959/104088092-612e2f00-5275-11eb-87a9-d829efd57629.png)

**Comment by kamalahmed** [comment]
Thank you for reporting this issue. For products in sale, the markup is coming from the Essential Addons for Elementor (EA) plugin directly. So, EA plugin needs to be translated. Translating only WooCommerce wont work.
