### ISSUE TITLE
EA Filterable Gallery doesn't work correctly

### ISSUE THREAD

**Issue by yusufbaykalbozkurt** [WPDevelopers/essential-addons-for-elementor-lite#592]
Hi there, I hope you and yours well! 
I recently wanted EA filterable gallery. But it has an issue at the first load of any browser or computer I tried. 
Once the page refreshed the problem solves automatically. I tried to write EA support I haven't heard from yet. Do you know what can be causing the problem and how can I solve this. I am going to share with you the screenshots. 
My website is currently under maintenance mood and I am hoping to launch next week. 
Thank you very much in advance. 
<img width="2560" alt="Screen Shot 2021-01-14 at 6 10 43 PM" src="https://user-images.githubusercontent.com/77468540/104661664-09d5f780-5697-11eb-9d22-45fcc4aa207e.png">
<img width="2560" alt="Screen Shot 2021-01-14 at 6 10 50 PM" src="https://user-images.githubusercontent.com/77468540/104661672-0b072480-5697-11eb-9da9-298cd86ed583.png">
<img width="2560" alt="Screen Shot 2021-01-14 at 6 16 46 PM" src="https://user-images.githubusercontent.com/77468540/104661677-0c385180-5697-11eb-9b1b-5a74181fe417.png">

Best
Yusuf

**Comment by abid112** [comment]
Hi @yusufbaykalbozkurt ,

Hope you're doing good!
I can see that one of our support agent replied to your query and guided you to regenerate assets on your website. Did you try that? 
You can reply back on our support channel so that our support team can investigate further.

Thanks!

**Comment by yusufbaykalbozkurt** [comment]
@abid112 Hi Abid, thank you! I hope you're doing good as well!
I tried to regenerate the CSS from adds on as well as on elementor. But the issue has been continuing. 

I tried to ask the theme developer, and he replied: There is no AJAX compatibility with this 3rd-party plugin (the complete plugins compatibility list). You can extend the theme compatibility using tips described here https://docs.artemsemkin.com/rhye/wp/customization/ajax-transitions.html#extending-plugins-compatibility This however not always possible. Turning AJAX navigation off from the Customizer panel will solve any issues like this one.

I haven't found a solution yet and since I wanted to use the EA filterable gallery I tried to disable the AJAX transition to this page. This looks like not showing a broken table but adds at least 15 seconds to the page to refresh with loader from the beginning. 

I checked the theme developers plugin compatibility page he says CSS code could solve this issue. 
Where I use EA Filtarable gallery at my portfolio page and there are only videos on that page means if I will be able to separate this mix plugin issue on this page without loader or refreshing the page I'd solve this.
Do you have any suggestions for me? 

Thank you very much for your help in advance.
Best
Yusuf
