### ISSUE TITLE
Multi Step Checkout Pro hooks

### ISSUE THREAD

**Issue by brandart** [WPDevelopers/essential-addons-for-elementor-lite#594]
Hooks like `woocommerce_checkout_order_review` are not possible.

Are there some checkout hooks that are possible to add, edit the checkout?

Or what is the way to customize the multistep checkout like this design:

![image](https://user-images.githubusercontent.com/31988348/105159148-0b784300-5b0f-11eb-8978-2284877004d0.png)

**Comment by abid112** [comment]
Hi @brandart ,

​I'm sorry to inform you that, currently we don't have any action hook in the Woo Checkout widget to customize the widget in function.
Hopefully, in the future, we will add support of action hook in all our widgets.
​Thanks!
