### ISSUE TITLE
Login form error

### ISSUE THREAD

**Issue by ELkoos** [WPDevelopers/essential-addons-for-elementor-lite#595]
On my production page, every now and then when I try to login using widget, it just shows recaptcha error - without showing recaptcha to checkin, and also, sometimes token error. 

Console reports:
cb=gapi.loaded_0:229 Uncaught {error: "idpiframe_initialization_failed", details: "Cookies are not enabled in current environment."}

All is configured using docs on your website.
I can use recaptcha keys in other forms just fine.

**Comment by kamalahmed** [comment]
Hi, Thank you for reporting this. Could you please make sure the cookie is not enabled in your browser settings or you are not using incognito mode?
Google may have made some changes to their API recently and it does not work in incognito mode or if cookies are blocked.  However, it should work in normal browser window.

**Comment by ELkoos** [comment]
Nope, this happens on normal login through not cleared cache in chrome on a
page that I visited for example 1 hour ago and then restarted my PC.
Krzysztof

niedz., 24 sty 2021, 12:13 użytkownik Kamal Ahmed <notifications@github.com>
napisał:
