### ISSUE TITLE
"Show Password" Icon is not showing up on Register Form

### ISSUE THREAD

**Issue by Nayanagr** [WPDevelopers/essential-addons-for-elementor-lite#596]
[atmos24.in/register](url)

**Comment by FariaAarin** [comment]
Hello @Nayanagr,
Sorry for the inconvenience caused. I assume your "Password visibility icon" is not enabled on your site. Could you please enable that? Please have a look: https://d.pr/i/95k45T 
Hope this will work.

Thank you.
