### ISSUE TITLE
elementor not work

### ISSUE THREAD

**Issue by alinotr** [WPDevelopers/essential-addons-for-elementor-lite#597]
POST https://usato.tecnifor.com/wp-admin/admin-ajax.php 500 (Internal Server Error)
send @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request&ver=5.6:4
ajax @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request&ver=5.6:4
s.ajax.s.ajax @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request&ver=5.6:7
send @ common.min.js?ver=3.1.1:2
sendBatch @ common.min.js?ver=3.1.1:2
f @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request&ver=5.6:2
setTimeout (async)
(anonymous) @ load-scripts.php?c=0&load[chunk_0]=underscore,jquery-core,jquery-migrate,backbone,jquery-ui-core,jquery-ui-mouse,wp-api-request&ver=5.6:2
addRequest @ common.min.js?ver=3.1.1:2
requestWidgetsConfig @ editor.min.js?ver=3.1.1:2
onStart @ editor.min.js?ver=3.1.1:2
onStart @ editor.min.js?ver=3.1.1:2
(anonymous) @ backbone.marionette.min.js?ver=2.4.5.e1:24
f.triggerMethod @ backbone.marionette.min.js?ver=2.4.5.e1:24
start @ backbone.marionette.min.js?ver=2.4.5.e1:25
13021 @ editor.min.js?ver=3.1.1:2
__webpack_require__ @ editor.min.js?ver=3.1.1:2
(anonymous) @ editor.min.js?ver=3.1.1:2
(anonymous) @ editor.min.js?ver=3.1.1:2

**Comment by abid112** [comment]
Hi @alinotr ,

That seems strange. Can you please check for plugin conflicts by following this: You can check for Plugin conflicts by deactivating all the third-party plugins one by one except for Elementor and Essential Addons. Simply go to your WordPress Dashboard and navigate to **wp-admin -> Plugins** and then, deactivate other Plugins.

Besides, you can switch to a different theme like Astra, Flexia, or Twenty Twenty. And, check back as well.

Let me know how it goes. Thank you!
