### ISSUE TITLE
EA Pro Display of widgets Problem

### ISSUE THREAD

**Issue by hiproductions** [WPDevelopers/essential-addons-for-elementor-lite#598]
I am using building courses with Learndash and Elementor and Essential Addons Pro - after recent update to EA Pro - I am having horrible display issues. All widgets suddenly are HUGE and stretch to eternity at a certain point in the course. If I disable EA Pro - they display fine - just as they display in the editor window. This has nothing to do with the browser as all browsers display this issue the same
![Screenshot_2021-02-03 Module Two Learn New Strategies - Thirsty Scholars Partnership](https://user-images.githubusercontent.com/48642736/106790807-f5f53400-664b-11eb-92ca-8554bd5ae074.png)
![Screenshot_2021-02-03 Elementor Module Two Learn New Strategies](https://user-images.githubusercontent.com/48642736/106790826-fdb4d880-664b-11eb-8eaa-88ed2312f5c0.png)

The first image is the problem - the second image is how the widgets appear in the editor and how it should appear. When I disable the EA Pro plugin - everything looks fine.

**Comment by abid112** [comment]
Hi @hiproductions ,

It seems like caching issue. Can you please try doing the following: To regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb

If the issue still persists, please create a support ticket with temporary admin access from here: https://wpdeveloper.net/support/new-ticket/

Our Support Team will get back to you and resolved this issue
Thank you
