### ISSUE TITLE
Tooltip not working on preview or live

### ISSUE THREAD

**Issue by alesys** [WPDevelopers/essential-addons-for-elementor-lite#599]
Hello,

Tooltip is working on edit mode: https://pasteboard.co/JMPhxgF.png.
But if I preview or publish, it shows the tooltip content below the item, and hovering doesn't trigger any action: https://pasteboard.co/JMPi2qF.png.

I'm using the latest version of Elementor Pro.

**Comment by abid112** [comment]
Hi @alesys ,

Sorry for the late response. It seems strange!
Can you please share your page URL so that I can check this on your page and assist you with this?

Thank you!
