### ISSUE TITLE
Twitter Feed Widget Bug

### ISSUE THREAD

**Issue by nickosmas** [WPDevelopers/essential-addons-for-elementor-lite#600]
Twitter feed widget stopped working

**Comment by FariaAarin** [comment]
Hello @nickosmas,

Sorry for the inconvenience caused. Please make sure you are using the latest versions of the Free (4.5.0) & Pro (4.3.1) plugins.
You can have a look at this doc for instructions: https://wpdeveloper.net/docs/automatically-tweet-wordpress-posts/

Hope this will help you.

Thank you!
