### ISSUE TITLE
Multiple Rows in Post Carousel

### ISSUE THREAD

**Issue by JoeHana** [WPDevelopers/essential-addons-for-elementor-lite#603]
Since the Post Carousel utilizes swiper and swiper is capable of having multiple rows in a carousel (slidesPerColumn) it would be great to have the very same option in the post carousel available.

**Comment by abid112** [comment]
Hi @JoeHana ,

Hope you're doing good.
Thanks for your awesome idea and suggestion. I'm adding this as a feature request for now. I will definitely discuss this with our team and if we get more such requests in the future, we will definitely implement it in our plugin.

Thank you for your suggestion. Have a nice day!
