### ISSUE TITLE
OffCanvas Update does not recognize H5P content any longer

### ISSUE THREAD

**Issue by elkbros** [WPDevelopers/essential-addons-for-elementor-lite#604]
I use the offcontent widget for H5P interactive shortcoded content. It worked great. However now if the widget is used on a page, it no longer plays the content or allows it to play anywhere else on the page, outside of the widget.
This must have been an issue with an update.

**Comment by abid112** [comment]
Hi @elkbros ,

That's strange!
Can you please create a support ticket from here: https://wpdeveloper.net/support/new-ticket/

Our Support Team will get back to you and resolved this issue
