### ISSUE TITLE
EA Duplicator: Cannot select multiple post types

### ISSUE THREAD

**Issue by ryanmacleod** [WPDevelopers/essential-addons-for-elementor-lite#605]
There is an option to enable the Duplicator for ALL post types or one single post type. It would be great if this could be a multi-select, so I can enable it on only the post types I need it for.

**Comment by abid112** [comment]
Hi @ryanmacleod ,

That's an awesome idea! I'm adding this as a feature request for now. We really appreciate your idea and suggestion. This will help us to improve Essential Addons for Elementor in the future.

Cheers!
