### ISSUE TITLE
Slider not displaying

### ISSUE THREAD

**Issue by lajevardu** [WPDevelopers/essential-addons-for-elementor-lite#610]
Hi the slider does not seem to display on the website however displays in elementor

**Comment by FariaAarin** [comment]
Hi @lajevardu,

I'm sorry to hear that. First of all, make sure that you are using updated versions of Essential Addons on your website. The current version of Essential Addons Free 4.5.1 and Essential Addons PRO 4.3.2
 
Afterward, make sure to regenerate assets. To do that, you can go to wp-admin -> Essential Addons then, switch to the 'Tools' tab and hit the 'Regenerate Assets' button. Check out this screenshot: https://prnt.sc/pvozsx
Also, make sure to Regenerate Files from wp-admin -> elementor -> Tools as well. Check out this screenshot: https://prnt.sc/r3b588
 
If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. 

Thank you.

**Comment by lajevardu** [comment]
Hi

It seems the regenerate files etc has totally broke the configuration of
the site and still hasn’t fixed the issue.


Thanks
Nathan

**Comment by FariaAarin** [comment]
Hello @lajevardu 

I'm sorry to hear that. Can you please share your website link with us? Also, Are you using any caching plugin? If yes, Please deactivate that plugin and try again. It seems a plugin conflict issue. Check this out for details: https://essential-addons.com/elementor/docs/plugin-conflicts-wordpress-website/

Let me know how it goes.

Thank you.
