### ISSUE TITLE
ELEMENTS ARE OVERSIZING MASSIVELY!

### ISSUE THREAD

**Issue by hiproductions** [WPDevelopers/essential-addons-for-elementor-lite#616]
Using Elementor Pro - Learndash - Essenatial Addons Pro - the Vimeo video is massively oversized despite regenerating assets repeatedly and clearing cache - for both elementor pro and EA
![Screenshot_2021-03-10 Module Two Getting a Risk Assessment Started - Thirsty Scholars Partnership](https://user-images.githubusercontent.com/48642736/110645627-0b5f0000-81ae-11eb-9d7e-151dbd309c0d.png)

**Comment by FariaAarin** [comment]
Hello @hiproductions,

Sorry for the inconvenience caused.  I would like to request you to create a support ticket [here](https://wpdeveloper.net/support/) so that we can check the issue from our end and solve it as soon as possible.

Thank you for your patience.
