### ISSUE TITLE
Filter Gallery Issue

### ISSUE THREAD

**Issue by josuemt158** [WPDevelopers/essential-addons-for-elementor-lite#620]
![image](https://user-images.githubusercontent.com/66498732/111184966-20a1a900-8577-11eb-82f6-ab4924f97664.png)
![image](https://user-images.githubusercontent.com/66498732/111185026-2d260180-8577-11eb-96c4-3f8ad5e0602f.png)

In elementor works irregular
In the publish web page not working

**Comment by FariaAarin** [comment]
Hello @josuemt158,

Sorry for the inconvenience caused. It seems like caching issue. Can you please try doing the following: To regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the **‘Tools’** tab and hit the **‘Regenerate Assets’** button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

If the issue still persists, please try clearing your browser cache or try another browser too.

Hope this will help you. Let me know how it goes. 

Thank you.

**Comment by josuemt158** [comment]
Thanks for the reply. I did every step. Tested with Edge Firefox android and Chrome and keeps with the error. 
![Screenshot_20210317_082915_org mozilla firefox](https://user-images.githubusercontent.com/66498732/111483907-dd704300-86fa-11eb-9934-d9d660846c13.jpg)
They are like overlap.

I am having now issues inside the elementor as well.

**Comment by josuemt158** [comment]
I started doing a new and the issue happened again. 
![image](https://user-images.githubusercontent.com/66498732/111487230-caab3d80-86fd-11eb-97a5-61b37d3c2c82.png)

**Comment by josuemt158** [comment]
I kept testing and it was SG Optimizer. As soon as I turned it off it worked well.

**Comment by khan-rafin-ahmed** [comment]
Hi @josuemt158,

Our plugin works fine with SG Optimizer too. Anyways, can you please try deactivating this following option: **'Minify HTML Output'**. Check out this screenshot: https://d.pr/i/FInjay

Let me know how it goes. Thank you!
