### ISSUE TITLE
Advanced Tooltip

### ISSUE THREAD

**Issue by Githubpowerusers** [WPDevelopers/essential-addons-for-elementor-lite#623]
Breaking the Elementor Popups currently. I found in the inspector an error:
[tippy]: `flipOnUpdate` is not a valid option
Would you please push out an update
Thank you

**Comment by abid112** [comment]
Hi @Githubpowerusers ,

It seems strange. I could not able to reproduce this issue on my end.
Can you please give me your page URL so that I can check and assist you with this?

Thank you!

**Comment by Githubpowerusers** [comment]
we don't have public access to the site. sorry.

Laszlo

**Comment by abid112** [comment]
@Githubpowerusers , In that case, you can create a staging website and clone your website there and share the URL with us. We will check back and assist you with this. 

Thank you!
