### ISSUE TITLE
Multiple Deprecation Notices

### ISSUE THREAD

**Issue by JoeHana** [WPDevelopers/essential-addons-for-elementor-lite#624]
Deprecated: Elementor\Scheme_Color since 2.8.0
Deprecated: Elementor\Scheme_Typography since 2.8.0

Elementor is heading up to 3.2.0 already, so this should be fixed quickly please.

**Comment by khan-rafin-ahmed** [comment]
Hi @JoeHana,

Thank you for your report. We are already aware of it and hopefully we will take care of this soon.

Cheers!

**Comment by JoeHana** [comment]
Well, this is somehow sad and weird now. Been using Essential Addons for quite some time now (also Pro) on multiple sites. And for some reason there are always troubles with every update. Just recently I've updated (can't remember from which version to which version) and suddenly all the Info Boxes had some empty P tags included which caused unnecessary spacing everywhere where it gets used. I didn't even report this since I already know the answer from you guys - it has been the same all the time over the past years. "We will check into this bla bla". In the end I had to replace each and every Info Box widget with another widget in order to replicate what I needed. This time I just used a default Elementor widget. Unfortunately I had probably hundrets of info box widgets across all those websites where I used Essential Addons - so it took quite a bit of time. In other cases some widgets lost their styling after an update or got messed up in any other way.

However, THIS here now is the topping on the cake: Elementor 2.8.0 has been released over a year ago and since then those functions/methods have been called for deprecation. But you didn't even took care of this in any way. Plenty of small "bug fix" updates have been released from you guys but THIS hasn't been even touched. Since I'm a webdeveloper myself it wasn't hard for me to identify the files where those deprecated methods are in use and just for testing I simply swapped them with the new ones and had no issues anymore. So in the end it is just swapping code in the majority of cases. Maybe there is one or the other case where more development is involved but in the majority of cases its just swapping the old code with the new one.

Are you too lazy for this? How can it be that you now have released an update but this has been again ignored? And what do you actually mean with "hopefully we will take care of this soon"? So there is a chance that you don't take care of this at all?

Well, nevermind - as I have already swapped out Essential Addons Info Box widget with another solution, and you're obviously not able to swap simple deprecated code lines with the new ones I guess I need to continue to swap from Essential Addons away again and find another solution in the long run. Hopefully one in which I can trust and where I feel comfortable to get better replies than just "we will see" or "if more people request" or "hopefully we will look into this".

Thank you.

**Comment by JoeHana** [comment]
So, Elementor 3.2.1 has been released now, bringing this deprecation notices up everywhere - wherever it is not visible it still gets printed in the log files and bloat them up rather quickly. When are you going to fix this? When will an update will be released which addresses this?

**Comment by khan-rafin-ahmed** [comment]
@JoeHana,

We have already resolved this and it's currently in testing phase. We are preparing a release this Sunday which will address this. Sorry about the inconvenience caused.

Thank you!

**Comment by khan-rafin-ahmed** [comment]
@JoeHana,

FYI: Patch is available in Branch "1337". If you want, you can test it. Thank you!

**Comment by JoeHana** [comment]
@khan-rafin-ahmed ok, looking forward to it and hopefully it will solve this. Altough I appreceate your quick response here now and your apology I would really love if in the future such things are getting addressed in a much professional manner, which means that such things should be taken care of much earlier and not when its nearly too late. Thank you

**Comment by JoeHana** [comment]
@khan-rafin-ahmed ok, I maybe check this out - but same issues actually go for the pro version as well and I guess there is no way to test both simultanously?

**Comment by khan-rafin-ahmed** [comment]
Hi @JoeHana,

Appreciate the feedback. It has been noted.

Anyways, yes, I can give you the Dev version for PRO as well. Can you please email us here: support[at]wpdeveloper[dot]net

Thank you!

**Comment by Hellsaya** [comment]
Hi, 

Same issue on my website. 

Yohann.

**Comment by khan-rafin-ahmed** [comment]
Hi @Hellsaya,

Are you using the Free version only? If so, please download the '1337' branch from GitHub. Your issue will be resolved.

Thank you!

**Comment by loorlab** [comment]
+1

**Comment by khan-rafin-ahmed** [comment]
Hi @JoeHana @loorlab @Hellsaya @ctc,

We have just released new versions of Essential Addons for Elementor. This error has been fixed. So everything will be good to go now! 

Thank you!
