### ISSUE TITLE
(Elementor pro) CPT, AE template unable to dynamically populate column background 

### ISSUE THREAD

**Issue by wyattsimpson98-code** [WPDevelopers/essential-addons-for-elementor-lite#625]
(Elementor pro) CPT, AE template unable to dynamically populate column background Image via AE post featured image, ACF image field or post featured image selector😢. Why is this a bug. It appears to pull in correct content when building but does not display the image on the live site. Additionally using a basic image widget works to pull the same content in dynamically. Just populating background images doesn’t work

**Comment by abid112** [comment]
Hi @wyattsimpson98-code , I'm not sure what you mean by the AE Post Feature Image? Can you please tell me which widget you're using? Also please give me a screenshot so that I can understand better.

Thank you!
