### ISSUE TITLE
Essential Addons for Elementor – Pro and Wordfence blocking Elementor Editor

### ISSUE THREAD

**Issue by GerardPerret** [WPDevelopers/essential-addons-for-elementor-lite#627]
Hi,
I got an issue using Essential Addons for Elementor – Pro and Wodefence plugin.
**When I enable Wordfence, the Elementor panel stays in a loading loop, doesn’t load anything and I can’t edit my pages or posts.**

If i disable EA i can edit with Elementor.

I found a post on Wordfence support (https://wordpress.org/support/topic/wordfence-prevents-premium-addons-from-working/#post-14244729) and they recommand to add two parameters to wp-config file
set_time_limit(300);
define('WP_MEMORY_LIMIT','300M');

This is fixing the issue, can you please me if this is the good way to process or if there is a related documentation on you side?
Regards

**Comment by khan-rafin-ahmed** [comment]
Hi @GerardPerret,

Seems like the issue was with Memory Limit. The way you have resolved the error by increasing the memory limit is actually the regular way how you deal with such error with Elementor not loading.

So, you should be all good to go, don't worry. Have a nice day!

**Comment by GerardPerret** [comment]
Thank you for your response, is ther any documention i can refer to?
   
  
  
   
    Le 28/03/2021 10:52, khan-rafin-ahmed ***@***.***> a écrit :
   
   
    
   
   
    
   
   
   Hi @GerardPerret,
   Seems like the issue was with Memory Limit. The way you have resolved the error by increasing the memory limit is actually the regular way how you deal with such error with Elementor not loading.
   So, you should be all good to go, don't worry. Have a nice day!
   —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
   
  
  
    Best Regards/Cordialement 
   Gérard PERRET | GPITS  | Cell + 33 6 08 87 73 06 | ***@***.***| www.gpits.fr
