### ISSUE TITLE
Bug in the Filterable gallery

### ISSUE THREAD

**Issue by ShadowsCrow** [WPDevelopers/essential-addons-for-elementor-lite#632]
In the item "Filterable gallery" with the following settings: 

![Screenshot_1](https://user-images.githubusercontent.com/66387724/113765397-93bfba80-96f2-11eb-8446-ddc774a42ba4.png)

We found an error related to the "load more button", when clicking on it to expand, the "show less button", disappears, soon after.

https://user-images.githubusercontent.com/66387724/113768031-c0290600-96f5-11eb-8d49-319db79ed74e.mp4

**Comment by FariaAarin** [comment]
Hi @ShadowsCrow,

Currently, the “Load More” button is working this way. Our dev team is working on the “Load More” button and hopefully, we will bring the feature just like you want in the future. Hope you'll understand.

Thank you.
