### ISSUE TITLE
Modal & Instagram Feed Errors

### ISSUE THREAD

**Issue by pauls92509** [WPDevelopers/essential-addons-for-elementor-lite#633]
**Staging site** - http://scorpion.iampaulscott.com

I have a modal BRANDS button (top right) in my header that when clicked, displays template content. The issue is, for some reason, part of the content will sometimes appear within the header below the button. This makes the header height increase and header elements get jumbled. If i refresh the page, it will often display correctly. But I can't tell my client or his customers to refresh their pages. It needs to just work.

In addition, within the Elementor Editor, the instagram feed displays posts one post per row instead of 4 columns per row as selected in the settings. This rearranges the rest of the page elements making it difficult to design.

I have tried turning off all other plugins (besides Elementor and EA). Any help would be greatly appreciated!

**Comment by abid112** [comment]
Hi @pauls92509 ,

Sorry for the late response. Hope you're doing good.
I could not reproduce this issue on your website actually. Can you please make a screencast and share it with us here so that I can understand it better?

Thank you!
