### ISSUE TITLE
Java Script not working

### ISSUE THREAD

**Issue by victormorenos** [WPDevelopers/essential-addons-for-elementor-lite#634]
Custom Js won't work inside elementor pages.

**Comment by abid112** [comment]
Hi there,

It seems fine on my end. Have a look: https://d.pr/v/h1qjhy
Make sure that you don't have any JS errors on your page. 

You can also regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Make sure to Regenerate Files from **wp-admin -> Elementor** -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb

Let me know how it goes.
Thank you!
