### ISSUE TITLE
Filterable gallery

### ISSUE THREAD

**Issue by awalls86** [WPDevelopers/essential-addons-for-elementor-lite#635]
I recently updated your plugin and now the images in my filterable galleries are not loading in Chrome or Firefox. What gives?
Version 4.6.1
I have built a lot of menus on my site using this element, so my site is now functionally worthless.

**Comment by awalls86** [comment]
Ok, so it seems that by updating all of my image files have been un-associated with this element. So now I have a job of re-associated more than a hundred pics. :( :( :(

**Comment by abid112** [comment]
Hi @awalls86 ,

It should not happen actually. Can you please regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

Let me know how it goes. Thank you.
