### ISSUE TITLE
Creative Button Issue

### ISSUE THREAD

**Issue by EliasFazel10296** [WPDevelopers/essential-addons-for-elementor-lite#636]
Creative Button Styling Section is incomplete after updating to 4.6.1 and previous created buttons also don't show any styling.

**Comment by rasel-wp** [comment]
Hi @EliasFazel10296,

Sorry to hear about the inconvenience. We are already aware of the issue and our developers are working on this to fix it. Hopefully, it will be fixed soon and released in our upcoming update.

Thanks.
