### ISSUE TITLE
Creative Button not working

### ISSUE THREAD

**Issue by michellemeiner** [WPDevelopers/essential-addons-for-elementor-lite#637]
Creative Button Styling Section doesn't work after updating to 4.6.1.

**Comment by rasel-wp** [comment]
Hi @michellemeiner,

Sorry to hear about the inconvenience. We are already aware of the issue and our developers are working on this to fix it. Hopefully, it will be fixed soon and released in our upcoming update.

Thanks.

**Comment by khan-rafin-ahmed** [comment]
Hi there,

We have fixed the issue with the new update. So, please make sure that you have updated Essential Addons Free and PRO to the latest versions & this issue will be resolved.

Thank you!
