### ISSUE TITLE
EA  Essential Addons Creative Button glitch

### ISSUE THREAD

**Issue by ThinkAheadZA** [WPDevelopers/essential-addons-for-elementor-lite#638]
The EA  Essential Addons Creative Button has removed the style elements for the button.
It was working this morning, however all that is left is a drop shadow now. I can't add colour to the button etc.
<img width="272" alt="Screenshot 2021-04-12 at 5 20 14 PM" src="https://user-images.githubusercontent.com/82396699/114419101-6de35b80-9bb3-11eb-99ca-583f32ada491.png">

**Comment by rasel-wp** [comment]
Hi @ThinkAheadZA,

Sorry to hear about the inconvenience. We are already aware of the issue and our developers are working on this to fix it. Hopefully, it will be fixed soon and released in our upcoming update.

Thanks.

**Comment by khan-rafin-ahmed** [comment]
Hi there,

We have fixed the issue with the new update. So, please make sure that you have updated Essential Addons Free and PRO to the latest versions & this issue will be resolved.

Thank you!
