### ISSUE TITLE
I'm Pro member, but not getting Pro privilege

### ISSUE THREAD

**Issue by helmizulkifli** [WPDevelopers/essential-addons-for-elementor-lite#640]
Hello. I have a lifetime unlimited EA plugin but after I updated the plugin recently, suddenly I don't have the privilege to use any Pro features. Please check the recent update. Thank you.
![Screenshot 2021-04-13 EA Plugins](https://user-images.githubusercontent.com/74693739/114513951-523c8b80-9c6d-11eb-8c20-df44fcb86a5f.png)

**Comment by rasel-wp** [comment]
Hi @helmizulkifli,

Sorry to hear about the inconvenience. We are already aware of the issue and our developers are working on this to fix it. Hopefully, it will be fixed soon and released in our upcoming update.

Thanks.

**Comment by khan-rafin-ahmed** [comment]
Hi there,

We have fixed the issue with the new update. So, please make sure that you have updated Essential Addons Free and PRO to the latest versions & this issue will be resolved.

Thank you!
