### ISSUE TITLE
new update makes some links/buttons disabled

### ISSUE THREAD

**Issue by adamf1631** [WPDevelopers/essential-addons-for-elementor-lite#641]
new update makes some links/buttons disabled. When I deactivate it the problem goes away.

**Comment by abid112** [comment]
Hi @adamf1631 , It seems strange actually!
Can you please regenerate from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

Let me know how it goes.
Thank you!
