### ISSUE TITLE
Deprecated: Elementor\Scheme_Typography is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Typography instead

### ISSUE THREAD

**Issue by kjsurgtech** [WPDevelopers/essential-addons-for-elementor-lite#642]
I got this error on my site today. How do I fix it?

**Comment by khan-rafin-ahmed** [comment]
Hi @kjsurgtech,

We have just released new versions of Essential Addons for Elementor. This error has been fixed. So everything will be good to go now! 

Thank you!
