### ISSUE TITLE
i m lookin for product grid

### ISSUE THREAD

**Issue by amitguptaindia** [WPDevelopers/essential-addons-for-elementor-lite#643]
installing this plugin elementor stoppd working

**Comment by abid112** [comment]
Hi @amitguptaindia ,

Can you please briefly explain with the screenshot what issue you're facing actually?
By mentioning the "Elementor stopped working", did you meant the widgets panel not loading? If so, you need to increase the memory limit. 

To increase the memory limit you will have to modify the wp-config.php file of yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

define('WP_MEMORY_LIMIT', '512M');

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Thank you.
