### ISSUE TITLE
Deprecated message popping up at top of page. 

### ISSUE THREAD

**Issue by tompatton2** [WPDevelopers/essential-addons-for-elementor-lite#645]
Error messaging pop up at the top of the page. I've hidden this for now, but it's still broken. This is also breaking the elementor editor. This is major issue and is breaking my entire site. Please advise. 

<img width="1440" alt="Screen Shot 2021-04-27 at 1 06 39 PM" src="https://user-images.githubusercontent.com/30573307/116306087-78782600-a759-11eb-9a1d-890c8a926e11.png">

Deprecated: Elementor\Scheme_Color is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Color instead. in /home/topkey/public_html/wp-includes/functions.php on line 5051

Deprecated: Elementor\Scheme_Typography is deprecated since version 2.8.0! Use Elementor\Core\Schemes\Typography instead. in /home/topkey/public_html/wp-includes/functions.php on line 5051

**Comment by abid112** [comment]
Hi @tompatton2 ,

Hope you’re doing good.
It seems this Deprecated error message comes from another plugin (If your **Essential Addons for Elementor** is up to date).

Can you please deactivate all the third-party plugins one by one except for **Elementor** and **Essential Addons** and try again.

Let me know how it goes.
