### ISSUE TITLE
Bug Filterable Gallery

### ISSUE THREAD

**Issue by marciocbamt** [WPDevelopers/essential-addons-for-elementor-lite#649]
An ellipse appears at the top of the image when you open the photo

**Comment by abid112** [comment]
Hi @marciocbamt ,

Can you please give me your page URL so that I can check and assist you with this?

Thank you!

**Comment by marciocbamt** [comment]
https://www.esperancactvg.com.br/estrutura/
[https://www.esperancactvg.com.br/wp-content/uploads/2021/05/E1.jpg]<https://www.esperancactvg.com.br/estrutura/>
ESTRUTURA - Esperança CT<https://www.esperancactvg.com.br/estrutura/>
Estrutura Conheça nosso espaço Oferecemos um ambiente harmonioso, agradável e aconchegante. TODAS EXTERNA INTERNA Contamos com uma área ampla e completa, com tudo que é necessário para estadia e tratamento adequados de nossos pacientes.
www.esperancactvg.com.br


[cid:6b80f3ee-92fa-452c-95a1-5fe3283a8c0f]

________________________________
De: Abid Hasan ***@***.***>
Enviado: quarta-feira, 19 de maio de 2021 22:27
Para: WPDevelopers/essential-addons-for-elementor-lite ***@***.***>
Cc: marciocbamt ***@***.***>; Mention ***@***.***>
Assunto: Re: [WPDevelopers/essential-addons-for-elementor-lite] Bug Filterable Gallery (#649)


Hi @marciocbamt<https://github.com/marciocbamt> ,

Can you please give me your page URL so that I can check and assist you with this?

Thank you!

**Comment by abid112** [comment]
Hi @marciocbamt ,

First of all sorry for the late response.
I can see that you're not using the EA Filterable Gallery anymore. 
We can still check the issue if you create a test page with EA Filterable Gallery and share the URL with me.

Thank you!
