### ISSUE TITLE
SVG's not embedding correctly

### ISSUE THREAD

**Issue by theapplesnaps** [WPDevelopers/essential-addons-for-elementor-lite#651]
In the Tool Tips widget, the SVG feature just needs to be switched over to a svg code. Instead it's using a img tag. Can you fix this? It's messing up my site ;(

**Comment by abid112** [comment]
Hi @theapplesnaps ,

It seems fine on my end. Have a look: https://d.pr/v/MYdDno
Can you please check for plugin conflicts by deactivating all the third-party plugins one by one except for **Elementor** and **Essential Addons**.

Let me know how it goes.
Thank you!
