### ISSUE TITLE
Change the Stock Out label

### ISSUE THREAD

**Issue by janoshke** [WPDevelopers/essential-addons-for-elementor-lite#653]
Hi, 
The EA Product Grid (WooCommerce) seems to be lacking the field to insert the custom text for "Stock Out" badge.
Is there a workaround until the issue is officially being solved?

Thanks.

Dejan

**Comment by FariaAarin** [comment]
Hi @janoshke, 

Hope you're doing well. Currently, we don't have this "**Stock Out"** text controller in Essential Addons for Elementor. Also, this string was not localized currently. However, Thank you for pointing this out. We will add this text controller or localize this string in the future version of Essential Addons for Elementor.

Have a good day!

**Comment by janoshke** [comment]
Hi @FariaAarin 

Thank you for your feedback. This would be a great option. Can't wait to have it.

Best regards,
Dejan

**Comment by abid112** [comment]
Hi @janoshke ,

We've released a new update today. You can now set your custom text for "Stock Out" products. Have a look: https://d.pr/i/tA3HUm

So make sure to update your Essential Addons for Elementor plugin to **v4.8.3** to get this feature.

Cheers!
