### ISSUE TITLE
Ninja Forms Elementor Bug

### ISSUE THREAD

**Issue by OGabrielS** [WPDevelopers/essential-addons-for-elementor-lite#654]
I can't see the form preview in elementor, no matter which pluggin I'm using, I drag the "Ninja Form" block but all that appears is a gray block with the wordpress or email icon, but when I click on it in "see changes" or enter the page the form is there. I think the problem is in the pluggin with Elementor

Steps to Reproduce: first i create a form on Ninja forms pluggin, then i open Elementor, use the ninja forms block from Essential addons, choose the form, but there is no preview, just appear a gray block with the ninja forms icon on the section, no matter what i do always have the same issue, and is just with ninja forms, the other forms customisers are working perfectly. But when i go to the final page, the form is working, the problem here is just with the preview in Elementor addon.

**Comment by FariaAarin** [comment]
Hello @OGabrielS,
Good Day!

​This is actually a **Ninja Form** issue. We're already aware of this. Even if you use the shortcode of **Ninja Form** in Elementor, It behaves the same.

​So, I would recommend you to contact Ninja Form support to get the proper solution. Link: https://ninjaforms.com/contact/

​Thank you!
