### ISSUE TITLE
FlipBox Not Loading

### ISSUE THREAD

**Issue by Jakeywags** [WPDevelopers/essential-addons-for-elementor-lite#655]
![Screenshot 2021-05-27 at 09 52 52](https://user-images.githubusercontent.com/84900359/119787317-5fd26b80-bed1-11eb-9a14-1e0eeec977a4.png)

Anyone know how to fix this?

**Comment by abid112** [comment]
Hi @Jakeywags ,

Sorry for the late response.
Can you please try to regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

If the issue still persists, please provide me your page URL that I can check!
Let me know how it goes. Thank you.
