### ISSUE TITLE
the pagination of essential addons

### ISSUE THREAD

**Issue by Duchemin-tony** [WPDevelopers/essential-addons-for-elementor-lite#656]
Hello, the pagination of essential addons does not work for the products, I have this error in the console, I have tested with another theme and deactivate all plugins but the error persists

Failed to load resource: the server responded with a status of 404 ()

I have the pro version

**Comment by arrasel403** [comment]
Hi @Duchemin-tony,

Hope you are doing well. Sorry for the late response.
I have got that our Support Team already replied to your ticket. Please recheck once your email. And if still, you have any issues, you can reply over your ticket. Our support team will check again and update you. And you can continue over there.

Thanks!
