### ISSUE TITLE
I updated the plugin and the testimonial slider stopped working

### ISSUE THREAD

**Issue by Rena42** [WPDevelopers/essential-addons-for-elementor-lite#657]
You can see the issue on my website's homepage https://quiltisrael.com

Thanks

**Comment by arrasel403** [comment]
Hi @Rena42,

It seems to a plugin conflict issue. Please, do a plugin conflict test. Check this out for help: https://essential-addons.com/elementor/docs/plugin-conflicts-wordpress-website/

If the issue still occurring, please create a support ticket from here: https://wpdeveloper.net/support/new-ticket/
Our Support Team will get back to you and resolved this issue.

Thank you!
