### ISSUE TITLE
after latest update info box svg color remains black

### ISSUE THREAD

**Issue by lamimershed04** [WPDevelopers/essential-addons-for-elementor-lite#659]
after recent update my info box uploaded icon color can't change 
its remain black and my design is collapsed

**Comment by lamimershed04** [comment]
![Screenshot (447)](https://user-images.githubusercontent.com/85755988/121716631-e015e500-cafd-11eb-8a51-e0e857ab71eb.png)

you can see its still black even i changed the color

**Comment by abid112** [comment]
Hi @lamimershed04 ,

It seems fine on my end.  Can you please regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: https://d.pr/i/23N5eb

Let me know how it goes. Thank you.

**Comment by lamimershed04** [comment]
Still Issue is Not Solved
i have regenerate both any other suggestions
The main issue is i have used Info Box in My entire web
The icon pack inside WordPress have no issues they are working fine
the issue is with the icons which i have uploaded from Flaticon and all
files are svg Files
Pls kindly Provide a solution
Thanks For your Support

**Comment by abid112** [comment]
Hi @lamimershed04 ,

Can you please provide me the SVG icon/file here so that I can test with that SVG file on my end and understand better.

Thank you!

**Comment by abid112** [comment]
Hi @lamimershed04 ,

Can you get back to us and provide the SVG so that we can test it?

Thank you!

**Comment by lamimershed04** [comment]
Sure, here it is.

**Comment by abid112** [comment]
Hi @lamimershed04 ,

I could not able to see your SVG here. Maybe you replied via email and attached it? Can you please provide the SVG image link from your WordPress Media Library so that I can access and download it?

Thank you!
