### ISSUE TITLE
Problema con Cuadricula de Productos

### ISSUE THREAD

**Issue by FarmaciaBelgrano** [WPDevelopers/essential-addons-for-elementor-lite#660]
Hola tengo un inconveniente con la configuración de mi modulo. En los productos que no tienen stock me sale un cartel redondo que no puedo eliminar y ademas me cambia el formato de Agregar al Carrito... pueden ayudarme por favor? adjunto imagen para que vean el problema.
![Captura de Pantalla 2021-06-12 a la(s) 18 42 25](https://user-images.githubusercontent.com/85808959/121789678-26c31800-cbae-11eb-825e-7bf472c4de25.png)

**Comment by FariaAarin** [comment]
Hi @FarmaciaBelgrano,

Hope you're doing well. Can you please share your website URL so that we can check ? Also, May I know which theme you're using?

Looking forward to hearing from you.

Thank you.

**Comment by FarmaciaBelgrano** [comment]
La URL es farmaciabelgranonqn.com.ar (por el momento lo que hice fue desactivar los productos que no tengo en stock para que éste problema se solucione y no quede estéticamente mal la cuadricula de productos)
El tema que uso es YHIT Proteo
Cabe aclarar que éste modulo, lo uso en modo móvil, para escritorio uso otro formato.
Quedo a su disposición para cualquier otro detalle.
Muchas gracias!

**Comment by FariaAarin** [comment]
Hi,

We've worked on your issue and you can find it fixed in "**1376_A**" branch. You can pull that branch and recheck. 

Let me know how it goes.

Thank you.

**Comment by FarmaciaBelgrano** [comment]
Hola! muchas gracias por solucionar el problema!. No entiendo dónde puedo encontrar la solución? me puede guiar por favor?

**Comment by FariaAarin** [comment]
Hi again,

I'm sorry I didn't get you properly. Can you please confirm me that you've been able to pull the **"1376_A**" branch? If you could do that then your problem should be solved.

**Comment by FarmaciaBelgrano** [comment]
Disculpa, no entiendo qué es la rama "1376A" ... me podrías guiar?

**Comment by FariaAarin** [comment]
Hi there, 
You can download the dev branch from here: https://d.pr/f/DgrFmk

Let me know how it goes.

Thank you.

**Comment by abid112** [comment]
Hi @FarmaciaBelgrano , 

We've also merged this in master branch(Live)
So you can now update your plugin instead of using the dev branch.

Thank you!
