### ISSUE TITLE
Calendar Not Updating from Google Calendar

### ISSUE THREAD

**Issue by crawpappy** [WPDevelopers/essential-addons-for-elementor-lite#661]
Hi,

I have a calendar embedded ([link](https://www.myforesttherapyrx.com/registration-and-calendar/)) that is connected to a Google Calendar and I'm having a heck of a time getting it to update with newly added events. As you can see it is connected because it shows past events. We've added another event on June 18th that is not displaying. I've tried increasing the max results field multiple times as well as double-checking the start and end dates.

Any help would be greatly appreciated.

**Comment by abid112** [comment]
Hi there,

Hope you're doing good.
Well, It actually should update within 1 hour.  I went through your website and saw that your event (18th June) appears on EA Event Calander perfectly.
