### ISSUE TITLE
 Uncaught TypeError: document.getElementById(...) is null

### ISSUE THREAD

**Issue by rafanas** [WPDevelopers/essential-addons-for-elementor-lite#664]
Unknown Console Error <img width="1244" alt="Screen Shot 2021-06-29 at 9 55 15 AM" src="https://user-images.githubusercontent.com/66040613/123820426-33d74b00-d8c0-11eb-9fba-1e3a01d2c054.png">

**Comment by abid112** [comment]
Hi @rafanas ,

It's possible that your asset file didn't generate correctly.
Can you please regenerate your asset from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

It should be fine!
Let me know how it goes.

Thank you!

**Comment by rafanas** [comment]
Thank you.

**Comment by rafanas** [comment]
Thank you!
