### ISSUE TITLE
Team Member Carousel

### ISSUE THREAD

**Issue by jephri1** [WPDevelopers/essential-addons-for-elementor-lite#667]
Hi there, the above addon is stretched outside my web page out to the RHS and I cant seem to be able to fix it. Disabled and enabled all the addons. Have them all off and only this one on. No difference. This addon is the main reason I paid for Essential Addons. Any suggestions

**Comment by abid112** [comment]
Hi @jephri1 ,

Can you please share your page URL so that I can check this issue on your website and assist you with this?

Thank you!

**Comment by jephri1** [comment]
All sorted thanks
