### ISSUE TITLE
css Droped 

### ISSUE THREAD

**Issue by mudawny** [WPDevelopers/essential-addons-for-elementor-lite#668]
site: https://ehabcenter.com/

I used Essential Addons with Elemntor in my hope mage to create a product carousel but CSS dropped down

**Comment by mudawny** [comment]
or JS File Sorry maybe dropped, Im not Programmer but you can proceed to check the issue

**Comment by abid112** [comment]
Hi @mudawny ,

It's possible that your asset file didn't generate correctly.
Can you please regenerate your asset from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Let me know how it goes.

Thank you!
