### ISSUE TITLE
essential addon 

### ISSUE THREAD

**Issue by bluebrushstore** [WPDevelopers/essential-addons-for-elementor-lite#670]
essential add on does not work after some editing with elementor, it force to enable safe mode 
please take an action to resolve this issue.

**Comment by abid112** [comment]
Hi @bluebrushstore ,

It's possible that your website is having low memory. You can check your memory limit by navigating to **wp-admin -> Elementor -> System Info**. Check out this screenshot: https://d.pr/WVKfum

You can install the following plugin on your website to take care of this: https://d.pr/f/D3Dik2

If that doesn't work, make sure to increase the memory limit. To increase the memory limit you will have to modify the wp-config.php file yours. Just above this line " /* That's all, stop editing! Happy blogging. */" add this following line of code:

**define('WP_MEMORY_LIMIT', '512M');**

You would find the wp-config.php file under your WordPress directory.

You can also read this blog to modify the wp-config.php file: https://wpdeveloper.net/troubleshoot-preview-loading-error-elementor/

If that doesn't work, please deactivate the Essential Addons elements you are not using especially the Dynamic Elements.

Let me know how it goes. 
Thank you!
