### ISSUE TITLE
woo product carousel glitch

### ISSUE THREAD

**Issue by mudasirsubhani21** [WPDevelopers/essential-addons-for-elementor-lite#671]
woo product carousel glitch the carousal is exceding the coulmn how can i fix?
www.seedbeej.com 
home page below featured products

**Comment by abid112** [comment]
Hi @mudasirsubhani21 ,

We're really sorry for the inconvenience.
I'm assuming you're using the Jetpack plugin. We have a conflict issue of Carousel elements with the Jetpack plugin.
Our dev team has already fixed this issue in one of the dev branches which will be released in the next update don't worry.

Thanks for your patience!

**Comment by abid112** [comment]
Hi @mudasirsubhani21 ,

We've just released a new update of **Essential Addons for Elementor(4.8.1)** where we fixed this issue.
So please make sure to update your EA plugin to resolve this issue.

After update your plugin please make sure to Regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT


Thank you!
