### ISSUE TITLE
Twitter Feed - posts are not displayed

### ISSUE THREAD

**Issue by Semplitechsrl** [WPDevelopers/essential-addons-for-elementor-lite#672]
Good morning,
I would like to report a problem with the Social Feed Elements "Twitter Feed": once we log in the Account the Consumer Key and the Consumer Secret are created automatically, but sometimes the connection with the Account does not work and Twitter posts are no longer displayed.

**Comment by abid112** [comment]
Hi @Semplitechsrl 

Sorry for the inconvenience.
We are already aware of this issue and our dev team has fixed this issue in one of our dev branches.
Here is the dev version I attached for you: https://d.pr/f/x0UO7j

So can you please download, install and replace this dev version on your website and let me know how it goes with this.

Note: Please take a full backup of your website before installing this dev version

Thank you!

**Comment by Semplitechsrl** [comment]
Hi @abid112,
unfortunately even after installing the Dev version the widget still does not show the tweets.

Some additional info: I’m using the “Twenty Twenty-One” theme and the WP version is 5.8.

Thank you!

**Comment by abid112** [comment]
Hi @Semplitechsrl , 

In that case, I would recommend you to generate **Consumer Secret** and **Consumer Key** from your Twitter and use that new keys on your wdget here: https://d.pr/i/frN1bj

Thank you!
