### ISSUE TITLE
Advanced Tab

### ISSUE THREAD

**Issue by marco7sette** [WPDevelopers/essential-addons-for-elementor-lite#673]
Advanced Tab it does not work

**Comment by abid112** [comment]
Hi @marco7sette ,

Can you please provide your page URL so that I can check the issue on your website and assist you with this?

Thank you!

**Comment by marco7sette** [comment]
www.mbtstudio.com   thanks

**Comment by abid112** [comment]
Hi @marco7sette ,

I've just replied to your topic in **WordPress** ORG: https://wordpress.org/support/topic/advance-tab-not-working/
I'm closing this issue from here.

Thank you!
