### ISSUE TITLE
Double New Account Email

### ISSUE THREAD

**Issue by bizdetail** [WPDevelopers/essential-addons-for-elementor-lite#675]
We are using the Edit Login / Register Form module, and are delivering a custom email via the "Notify user by email" register action. 

The issue we have is that the email is delivered to the new users email two times. 

When we turn off the functionality, and use the default new user notification email, it is only delivered once. 

We are running 4.8.3 and WP 5.8

**Comment by abid112** [comment]
Hi @bizdetail , 

Since you've created a topic on WordPress Org aswell, I'm handling this topic/issue there: https://wordpress.org/support/topic/two-user-registration-emails/

Hence I'm closing this issue from here.
Thank you!
