### ISSUE TITLE
The "Typing words" element issues

### ISSUE THREAD

**Issue by Rahulnagarajan** [WPDevelopers/essential-addons-for-elementor-lite#676]
On my site, Typing Word Element is not working. In between typo words are not coming.
Site id: http://trackdfect.com/
and 
https://stage.trackdfect.com/

**Comment by abid112** [comment]
Hi @Rahulnagarajan ,

Hope you're doing good. I went through your both websites.
It seems you're using **EA Fancy Text** on this website:  https://stage.trackdfect.com/ which is working fine. Have a look: https://d.pr/v/AkqFTY

So can you please clean your browser cache or try from the Incognito browser?

Let me know how it goes.
Thank you!
