### ISSUE TITLE
Filterable gallery bug - Wordpress

### ISSUE THREAD

**Issue by Carosteams** [WPDevelopers/essential-addons-for-elementor-lite#677]
Hello,

I am contacting you because I have a problem with my filterable gallery.  First of all, it won't filter as it should and when I type something inside the search bar it won't work.

Do you know how can I solve this?

Thank you so much

https://user-images.githubusercontent.com/88940302/129453058-2543ca4b-c0d1-4bcd-bea8-ed58fdd8594c.mp4

**Comment by NahidHasanTushar1** [comment]
Hi @Carosteams,

We've replied to the ticket that you've created on our support platform.

Thank you!
