### ISSUE TITLE
lightbox modal randomly stopped working one day

### ISSUE THREAD

**Issue by Dave11971** [WPDevelopers/essential-addons-for-elementor-lite#679]
after not updating my website for over a week the lightbox modal widget randomly stopped opening the lightbox and when I tried to re-add it the settings did not work as they used to in regards to making the image trigger larger.

**Comment by abid112** [comment]
Hi @Dave11971 ,

It seems like caching issue. Can you please regenerate assets from **wp-admin -> Essential Addons** then, switch to the ‘**Tools**’ tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

Let me know how it goes. Thank you.
