### ISSUE TITLE
Can't disable integration related elements

### ISSUE THREAD

**Issue by betterts** [WPDevelopers/essential-addons-for-elementor-lite#680]
These items do not appear on the elements enable/disable page and cannot be disabled from the elementor widget panel, even when the integrations are not installed:
- EasyJobs Career Page
- Crowdfundly All Campaign
- Crowdfundly Organization
- Crowdfundly Single Campaign
- EmbedPress
- ReviewX Woo Review

**Comment by rasel-wp** [comment]
Hi @betterts,

Sorry for the inconvenience caused.
Currently, we don't have an option for disabling these widgets. These are our Promotional widgets.

Hope you understand. Let me know if you have any other queries. Thanks!
