### ISSUE TITLE
Feature List problem

### ISSUE THREAD

**Issue by MisteriyaTX** [WPDevelopers/essential-addons-for-elementor-lite#681]
Update: Now I see this problem not only with Essential addons widgets :(

I trying make list of your Feature List element, when copy or save it as tamplate.
Until this point everyfing okay.
If there is only one Feature List widget on the page, then everything is okay too. But if I insert a copy of this widget (or template) and start editing, both lists are change. Looks like both lists are connected. I need to make one sheet on the right, copy it on the left and edit it with different text. 
And also it editing content on different page

**Comment by sadmansakibnadvi** [comment]
Hi there,

That seems strange. I could not able to reproduce the issue on my end.
Can you please check for plugin conflicts by deactivating all the third-party plugins one by one except for **Elementor** and **Essential Addons.** Simply go to your **WordPress Dashboard** and navigate to **wp-admin -> Plugins** and then, deactivate other Plugins.
Let me know how it goes. Thank you!
