### ISSUE TITLE
Reading Progress Bar does not work with Elementor global color as Fill Color

### ISSUE THREAD

**Issue by tomek-sienicki** [WPDevelopers/essential-addons-for-elementor-lite#682]
Hi WPDev,
Reading Progress Bar does not work with Elementor global color as Fill Color. When I choose the predefined global color it falls back to default green, while clicking on color box will force it to use. Background color works well with both global and custom color set.
WP 5.8, Elementor 3.4.2, EA 4.8.4

**Comment by sadmansakibnadvi** [comment]
Hello @tomek-sienicki,

Sorry for the inconvenience.

We are aware of this issue. Our dev team is working on this issue and this will be fixed in the future update of **Essential Addons for Elementor.** For the time being, you can manually pick the color.

Thank you.

**Comment by abid112** [comment]
Hi @tomek-sienicki ,

Can you please check now? Recently we've worked on our asset system and made it compatible with the Elementor global color. So your mentioned issue should be fixed now. Can you please check and let me know how it goes now?

Cheers!
