### ISSUE TITLE
Bug with the layout

### ISSUE THREAD

**Issue by amtsites** [WPDevelopers/essential-addons-for-elementor-lite#684]
Hi, I created a section for my portfolio on my website and sometimes this bug happens. I'll send how is the normal way and how the bug is:
![Captura de Tela (22)](https://user-images.githubusercontent.com/89176112/130108945-03426040-95b8-470d-a537-cedb57e13ba7.png)
![Captura de Tela (23)](https://user-images.githubusercontent.com/89176112/130111714-fab6d9cc-1d2c-4ffe-ae89-1537120c9e23.png)
![Captura de Tela (24)](https://user-images.githubusercontent.com/89176112/130111722-0b029c24-4012-484d-89e7-8d18b84678f4.png)
![Captura de Tela (25)](https://user-images.githubusercontent.com/89176112/130111732-a88a5308-ebfc-4381-bac0-904b80b34775.png)

**Comment by sadmansakibnadvi** [comment]
Hello, @amtsites,
Good day. Sorry for the inconvenience.
The filterable gallery is working fine on my end.
It seems like caching issue. Can you please try doing the following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: [https://d.pr/i/OeGVUT]
Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools as well. Check out this screenshot: [https://d.pr/i/23N5eb]

If the issue still persists, please try clearing your browser cache or try another browser too.

You can also check if there is any clash between the plugins or not. Please disable all other plugins except Elementor and Essential addon then check.

Let me know how it goes. Thank you.
