### ISSUE TITLE
anchor link support for nested ea advanced tabs

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#686]
I have configured an advanced tab addon in a way that contains a template which itself contains another advanced tabs addon, to get 4 tabs where each tabs contains another 4 tabs. I've waited for a long time an anchor link support and that was recently added but it not support my configuration. I can make anchor link works for the main 4 tabs but not for the nested ones, any clue on how I can get it works? Thank you in advance (tabs)

**Comment by FariaAarin** [comment]
Hi @Azertooth,

Thank you for pointing this out. Actually, our dev team is already aware of this issue and they're working on it. Hopefully, you'll find it fixed in our future update. 

Thank you for your patience.

**Comment by Azertooth** [comment]
With the latest update you introduced `EA Advanced Tabs & Advanced Accordion | Custom ID Anchor not working with links on same page` but again, for nested tabs is kinda broken: the links works and it select the right nested tabs (highlighting the title) but the content of the tabs do not match, it reports the content of the first nested tabs from left
