### ISSUE TITLE
Login > lost password

### ISSUE THREAD

**Issue by CrisDurden** [WPDevelopers/essential-addons-for-elementor-lite#687]
In the login and registration tool, the link for password recovery (lost password) is not working. Please fix this tool. 
Awaiting return. 
Hugs.

**Comment by abid112** [comment]
Hi @CrisDurden ,

Hope you're doing good.
I just tried and it seems fine on my end. Have a look: https://d.pr/v/GzoT5Y

I would recommend you to check for plugin conflicts by deactivating all the third-party plugins one by one except for **Elementor** and **Essential Addons**. Simply go to your WordPress Dashboard and navigate to **wp-admin -> Plugins and then, deactivate other Plugins**.

Let me know how it goes.
Thank you!
