### ISSUE TITLE
Not able to show custom post type taxonomy in Post carousel widget

### ISSUE THREAD

**Issue by lesvauriens** [WPDevelopers/essential-addons-for-elementor-lite#689]
Hi,

I'm using the Post Carousel widget from EA with Elementor.
Everything is fine and I'm able to query custom post types with there custom taxonomy (all created with CPT UI). It's great.
But in "Layout Settings", when I check "Show Post Terms", it only allow me to show Category or tags, but not the custom taxonomy linked to posts. So nothing is showed and I'm disappointed.

Can you make a small improve and add the correct custom taxonomy to the list?  
Or at least provide me some help to do a patch until it's implemented?

Thanks,

**Comment by sadmansakibnadvi** [comment]
Hello there,

Sorry for the inconvenience.

I tried to reproduce the same issue. Please check this screenshot: https://d.pr/vGo700. It is working fine from my end. 

So, please **create a support ticket** here: https://wpdeveloper.net/support/ - our team will reach out to you, don't worry. 

Thank you.

**Comment by lesvauriens** [comment]
Hi,
Yes, as I said, everything is working fine with the query filter.
But go to "Layout Settings", check "Show Post Terms" and you'll see that you can just select "Category" and "Tags", and you'll not be able to choose "Custom category".

Thanks,

**Comment by sadmansakibnadvi** [comment]
Hello again,

It seems strange. please create a support ticket here: https://wpdeveloper.net/support/ - Our team will look into your issue.
