### ISSUE TITLE
 "Feature List" Widget: Icon Size is ignored

### ISSUE THREAD

**Issue by zerfl** [WPDevelopers/essential-addons-for-elementor-lite#690]
Hello,

**Version**
- WordPress v5.8
- Elementor v3.4.3
- Elementor Pro v3.4.1
- Essential Addons for Elementor v4.9.0 (Lite)

**Description**

The "Feature List" widget is ignoring the icon size a user sets inside the widget settings. Changing the icon size in the "feature list" widget is not correctly applied when viewing a page that uses this widget. It only works in the admin side of things while using the Elementor editor.

**Cause**
**_Note: This problem only happens when using Elementor's "Internal Embedding" CSS Print Method._**

There's a [CSS specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) issue within the Feature List widget. The default widget selector `.elementor-widget-eael-feature-list .eael-feature-list-items .eael-feature-list-item .eael-feature-list-icon-box .eael-feature-list-icon` sets `font-size: 30px` which translates to the icon size. The selector is too specific and will always override the custom setting.

**Visualisation of the cause**
<img width="694" alt="Screenshot 2021-09-02 at 15 44 30" src="https://user-images.githubusercontent.com/219458/131855035-9955e691-7395-461d-b681-59df51fe1ffb.png">

Steps to reproduce:
- Create a new page and add the "Feature List" widget. Change the icon size in the editor to e.g. 10.
- View the page in the front-end and notice how the icon sizes are not 10 but 30.

**Comment by rasel-wp** [comment]
Hi @zerfl,

Sorry for the inconvenience caused.
I have tried to reproduce the issue, but I have got it is working well on my side. I have tried with WordPress version 5.8, Elementor Free v3.4.3, Elementor Pro v3.4.1, and Essential Addons for Addons v4.9.0 (lite). You can check this screen record: https://d.pr/v/ELpLmQ

It seems like a caching issue. Can you please try doing the following: To regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the ‘Tools’ tab, and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://prnt.sc/r3b588

If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. Thank you.

**Comment by zerfl** [comment]
Hi @rasel-wp,

thanks for getting back to me.

After some testing the same day I noticed that the issue was caused by enabling Elementor's "Internal Embedding" (CSS Print Method Option). Setting it to "External File" does override the styles properly and the widget looks all proper now.

Thanks for your time!
