### ISSUE TITLE
Broken layout after few days! news ticker and blog post widgets,  facebook widgets as well 

### ISSUE THREAD

**Issue by nayeem07007** [WPDevelopers/essential-addons-for-elementor-lite#693]
Here are the screenshots for the issue 
https://prnt.sc/1ri2ywp
https://prnt.sc/1ri343o

Sometimes it showing well 

here is the current website https://sbgcp.loyalcoder.com/

but in the builder, it looks good 
https://prnt.sc/1ri3hvo
https://prnt.sc/1ri3kwi

**Comment by sadmansakibnadvi** [comment]
Hello @nayeem07007,

Hope you are having a good day. Sorry for the delayed response.

I checked your site. It seems fine from our end. However, scrutinizing your given screenshots, it seems like it might be asset regenerate issue.

If it still occurs in the future, You can do the following:
To regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the **‘Tools’** tab and hit the ‘**Regenerate Assets**’ button. Check out this screenshot: https://d.pr/i/OeGVUT

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://d.pr/i/23N5eb

If the issue still persists, please try clearing your browser cache or try another browser too.

Let me know how it goes. Thank you.
