### ISSUE TITLE
advanced accordion bug: no access to saved templates

### ISSUE THREAD

**Issue by wgnknt** [WPDevelopers/essential-addons-for-elementor-lite#700]
Hello,
i've been using the 'Advanced Accordion' feature a lot on my customer's website.
Unfortunately, it stopped working properly some weeks ago: When 'Saved Templates' is selected as content type, the list of saved templates won't appear anymore. 
The old accordions can still access my templates and display correctly. But I'm not able to replace the contents or to build new ones, which is pretty unfortunate.
Of course I'm using the latest versions of Elementor and Essential Addons.
Thanks in advance!

**Comment by rasel-wp** [comment]
Hi @wgnknt,

Hope you are doing well. Sorry for the inconvenience caused.
It seems really very strange. I have checked on my site and it is working well. Check this screen record: https://d.pr/v/Lyw7Mk

Please regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the ‘Tools’ tab, and hit the **‘Regenerate Assets’** button. Check out this screenshot: https://prnt.sc/pvozsx

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools** as well. Check out this screenshot: https://prnt.sc/r3b588

If the issue still persists, please try clearing your browser cache or try another browser too.

If still, you are facing any issues. Please create a support ticket from here: http://wpdeveloper.com/support/new-ticket
with details.

Our support team will check and get back to you as soon as possible.

Thanks!
