### ISSUE TITLE
EA Filterable Gallery only works in Elementor Editor mode

### ISSUE THREAD

**Issue by KK-1000** [WPDevelopers/essential-addons-for-elementor-lite#703]
Hello,

I've recently seen that my filterable gallery doesn't work anymore in live mode :
- The filters doesn't works (nothing happens when we click on it)
- The "load more" button bring me to the top of the page when I click on it.

What is interesting is that everything works fine in the Elementor Editor mode.
If you wanna check it, here's the link to the live website page: https://www.uptale.io/en/success-stories

What I've tried for now:
1. Regenerate assets in essential addons dashboard > tools
2. Regenerate files and CSS in Elementor > tools > dashboard
3. Clear all the website cache 

It's still not working when live.

**Comment by sadmansakibnadvi** [comment]
Hello there,

Good day. Sorry for the late response.

I just checked the page and I see lots of errors in the console. Please check this screenshot: https://d.pr/i/nsfGwg

Can you please check for plugin conflicts by following this: You can check for Plugin conflicts by deactivating all the third-party plugins one by one except for Elementor and Essential Addons. Simply go to your WordPress Dashboard and navigate to wp-admin -> Plugins and then, deactivate other Plugins.

Let me know how it goes. Thank you!

**Comment by KK-1000** [comment]
Hey! Thank you for your quick answer.
It was actually due to Monster Insight's coding!

I've fixed it ;)
