### ISSUE TITLE
Divide by zero in Post Grid Essential Addons Version 4.9.6

### ISSUE THREAD

**Issue by Nicki-Bladal** [WPDevelopers/essential-addons-for-elementor-lite#705]
Getting following error:

Warning: Division by zero in /var/...../public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/Elements/Post_Grid.php on line 1088

**Comment by amitbarai013** [comment]
Hi @Nicki-Bladal ,

Hope you are doing well.



Our developer is checking this issue deeply. In the meantime, you can use this developer version from this link: https://d.pr/f/Kjs5nT


Let me know how it goes.

Thanks.

**Comment by abid112** [comment]
Hi @Nicki-Bladal , 

We've fixed this issue in the latest EA 5.0. Feel free to update the plugin to get this resolved.

Thank you!
