### ISSUE TITLE
EA Protected Content, how to limit failed attempt?

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#706]
How can I mitigate brute force attack to the protected content password field?

**Comment by amitbarai013** [comment]
Hi @Azertooth ,

Greetings.

In our **EA Protected Content** Element, you will get the facility to protect the content only. But unfortunately, you will not get any advanced feature that can mitigate the Brute Force attack. However, I will discuss this with the developer team. Hope this will be implemented in future updates.

Thanks.
Have a good day!
