### ISSUE TITLE
Advanced Tabs & Post Grid Bugs on Mobile Browsing

### ISSUE THREAD

**Issue by askpttim** [WPDevelopers/essential-addons-for-elementor-lite#707]
Hello,

Last week I noticed that I started to have a couple of bugs present in **Essential Addons Elementor Kit** plug-in that is showing up on **mobile** browsing only.

1. **Advanced Tabs** not working properly. I can see the Tab Titles, but there is no caret and no content below each tab is displayed. This is problematic for me as my online store is using these advanced tabs to house digital products and, currently if someone is browsing my shop in mobile, they cannot see any of my products in the tab categories.

2. **Post Grid** is not working properly. There is a grey box showing up that is located directly below each card image. Again, this is seen in mobile browsing only as well. I have seen this bug show up briefly once before, but it was corrected with the last plug-in update.

Please try to update the Essential Addons plug-in to correct these issues.

Cheers!

**Comment by sadmansakibnadvi** [comment]
Hello there,

Good day. Extremely sorry for the inconvenience.

Can you please create a support ticket from here so that we can check from your end: https://wpdeveloper.com/support/new-ticket

Thank you.
