### ISSUE TITLE
Add to cart button icon

### ISSUE THREAD

**Issue by AbishekLalKumar** [WPDevelopers/essential-addons-for-elementor-lite#709]
in the product carousel, the add to cart button is working but not showing the cart icon
![Screenshot (107)](https://user-images.githubusercontent.com/52396571/144973303-ae30380d-f0de-4d29-89f1-a0efa5a136ae.png)

**Comment by onlykawshar** [comment]
Hello there, 

I have checked your query. And we are already aware of this issue. I request you to download & use this Dev Version from this link - https://d.pr/f/5XD3Wx

Hopefully it will help you to solve this issue. Let me know how it goes. 

Thank you

**Comment by abid112** [comment]
Hi @AbishekLalKumar , we've fixed this issue in the latest production EA version as well. Feel free to update the latest EA 5.0.1 to get this resolved!

Thanks!
