### ISSUE TITLE
Overlay Clickable Woo product carrousel

### ISSUE THREAD

**Issue by MonsieurClutch** [WPDevelopers/essential-addons-for-elementor-lite#710]
Hello, Is it possible to make the carrousel overlay (Like in the Preset 2) clickable to go directly to the product page?
It would be a great thing to have. 

Thanks a lot,

**Comment by sadmansakibnadvi** [comment]
Hello @MonsieurClutch,

Greetings. Hope you are doing well.

Well, you can do it by enabling the image clickable option. Please check the screenshot: https://d.pr/i/QE5KHL. It would lead the visitor to that specific product.

Hope this solves your issue. Thank you.

**Comment by MonsieurClutch** [comment]
Thanks for your answer, but it's not working with the overlay. 
With preset 1 where you have the image above the text it's good, you can click on the image as you said. 
But with preset 2 where you have an overlay over the image with the text, it's not working. Maybe you can fix this? 

Best regards, 

Corentin

**Comment by sadmansakibnadvi** [comment]
Hello there,

Greetings. 

Yes, it works for preset 2 as well. Please check this gif: https://d.pr/i/cmwlc6

If you are having the issue Can you please create a support ticket with temporary login access from here so that we can check from your end: https://wpdeveloper.com/support/new-ticket

Thank you.

**Comment by sadmansakibnadvi** [comment]
Hello again,

Good day.

As we didn’t hear from you since then, We are assuming your problem has been resolved. If you still have any questions feel free to knock us anytime.

Thank you.
