### ISSUE TITLE
Advanced Tabs tags show the content of the first tab when navigated to through their hashtag.

### ISSUE THREAD

**Issue by yahneedjohn80** [WPDevelopers/essential-addons-for-elementor-lite#712]
This happened when I updated today to the newest version. Now when I click on a link with a tab hashtag it takes me to that tab but shows the content of the very first tab unless I click on the tab I want manually. It used to do this automatically.

![image](https://user-images.githubusercontent.com/60203773/146599673-366952cd-7afb-4839-a19d-5dea6539a275.png)
What it should show is this instead.
![image](https://user-images.githubusercontent.com/60203773/146599717-5b5a59cc-d861-4661-b43b-a860bdd696b4.png)

**Comment by sadmansakibnadvi** [comment]
Hello there,

Greetings. 

Sorry for the inconvenience and thanks for pointing this out. We have found the issue as well. I have already informed our dev team about it and they are working on it. 

I will update you as soon as the issue is fixed. Thank you and have a great day.

**Comment by sadmansakibnadvi** [comment]
Hello there,

We have fixed this issue on a Dev Version. Please download and install this version from this link - https://d.pr/f/V9eoaO

Hopefully, it will help you to fix your issue. ​​Let me know how it goes.

Thank you.

**Comment by abid112** [comment]
Hi @yahneedjohn80 ,

We've fixed this issue in the latest version of Essential Addons for Elementor **v5.0.2**
Feel free to update the plugin to get this resolved!

Thanks!
