### ISSUE TITLE
Problems with your plugins

### ISSUE THREAD

**Issue by graphicgrooves** [WPDevelopers/essential-addons-for-elementor-lite#713]
For the past couple of months, there has been a problem with your template. Last month I had to deactivate all the Woocommerce plugins because your template wouldn't work correctly. Now, I'm having to delete the essential plugin that you created on my site to make my website look correct. 

The hosting company told me that these plugins are causing a problem
#0 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/controls-stack.php(2231): Elementor\Exhibz_Testimonial_Widget->_register_controls()
#1 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/controls-stack.php(480): Elementor\Controls_Stack->init_controls()
#2 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/widget-base.php(175): Elementor\Controls_Stack->get_stack()
#3 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/controls-stack.php(286): Elementor\Widget_Base->get_stack()
#4 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/controls-stack.php(2322): Elementor\Controls_Stack->get_controls()
#5 /home1/thepoxa9/public_html/tple/wp-content/plugins/elementor/includes/base/controls-stac in /home1/thepoxa9/public_html/tple/wp-content/themes/exhibz/components/editor/elementor/widgets/testimonial-slider.php on line 141

I'm not sure why they are causing a problem but my website looks like this because there is a problem. Can you please tell me what's wrong and how to fix this mess? 
![Screenshot (192)](https://user-images.githubusercontent.com/85893191/146817993-2b8471e3-db9b-4ad1-aabf-511036ebb93e.png)

**Comment by amitbarai013** [comment]
Hi @graphicgrooves ,

Hope you are doing well.

I have checked the errors that you sent. But the errors are not created due to our plugin/themes/elements. These errors are related to the Elementor plugin and the theme that you are using. Please check this screenshot: https://d.pr/i/NfzVwH

Please contact the respective support team to get the proper support.

Thanks.
