### ISSUE TITLE
the_content() error when the plugin is active

### ISSUE THREAD

**Issue by kauefidelix** [WPDevelopers/essential-addons-for-elementor-lite#714]
The plugin worked fine for a while, but after i created a login page, it gave me the “Sorry, the content area was not found in your page. You must call
the_content function in the current template, in order for Elementor to work on this page.” error when trying to edit, i used the login, register and advanced tabs addon.
edit: disabling the advanced tabs stops the error, inside of it in my header menu i linked the login and register templates.

**Comment by abid112** [comment]
Hi @kauefidelix ,

It generally happens for the page layout. You need to select the correct page layout.
Please follow this doc: https://wpdeveloper.com/content-area-not-found-error-elementor/

Elementor also have a doc to solve this issue as well: https://elementor.com/help/the-content-area-was-not-found-error/

Thank you!
