### ISSUE TITLE
Global widget

### ISSUE THREAD

**Issue by mahmoudsrdar** [WPDevelopers/essential-addons-for-elementor-lite#715]
When I save a widget as global and use it in another page, it resets itself like I added it from the widget section

**Comment by abid112** [comment]
Hi @mahmoudsrdar ,

I could not able to reproduce this issue on my end. Have a look: https://d.pr/v/0r3yZv
Which widget you've tried please let me know so that I can try with that particular widget and check again.

Thank you!

**Comment by abid112** [comment]
Hi, there. Can you please get back to us? Has your issue been resolved yet?
Let us know so that we can help you out. Thank you!

**Comment by mahmoudsrdar** [comment]
Hi there
yes, the problem has been fixed, maybe after I updated Elementor and Essential Addons.
Thank you.
