### ISSUE TITLE
Redirect to another link in pricing table footer button

### ISSUE THREAD

**Issue by saifullahsiddique** [WPDevelopers/essential-addons-for-elementor-lite#718]
Hi, I've built a pricing table and there are a button in pricing table footer section. The button contains add-to-cart link as well. Is it possible to redirect and add to cart at a time in the pricing table footer button ??

**Comment by sadmansakibnadvi** [comment]
Hello there,

Greetings.

Unfortunately, there isn't any workaround on what you are expecting to do. Though thanks for your idea. It would help us to improve our plugin.

Have a great day.

**Comment by saifullahsiddique** [comment]
Thanks for your feedback.
