### ISSUE TITLE
WooProduct Gallery - toggle active category filter when coming from URL

### ISSUE THREAD

**Issue by mariyanh** [WPDevelopers/essential-addons-for-elementor-lite#719]
Hello,

I am having a really nice experience with your Woo Product Gallery module.

I build my Product Archives with it and want to use it for Category Archives as well.
So now I am trying to figure out how to set the active category to the filter when landing on a certain category.
For example : /website.com/product-category/category/

I can see each tab has its own data-terms, data-id, etc. But can it be set active from the URL or I must create some kind of listener?

Thanks,
Mariyan

**Comment by amitbarai013** [comment]
Hi @mariyanh ,
Hope you are doing well.

If you use the source as **_Dynamic_** from the **Product Settings** option in **Woo Product Gallery**, then the product from the related category will be visible. Please check this **screencast** that I created for you to show the detail: **https://d.pr/v/9lfLvs**

Let me know how it goes.
Thank you.
