### ISSUE TITLE
EA Accordion Saved Template not responsive

### ISSUE THREAD

**Issue by tsukidoki** [WPDevelopers/essential-addons-for-elementor-lite#720]
Hello, 

I'm current using EA Advanced Accordion and I put in my content using the Saved Templates method. However, it doesn't become responsive at all. I've cleared cache, edited the saved templates themselves, everything. The saved templates themselves are entirely mobile responsive but not when I put them into the accordion. The issue can be found on https://tsukidoki.art/comms/.

Thanks!

**Comment by AmitPaul-akp** [comment]
Hello @tsukidoki, 

Greetings. Hope you're doing good. 

Sorry for the delay to reach you. Well, I have just checked your site, and your Accordion with templates works perfectly on responsive mode there. Hope it has been fixed now. 

However, if you still find any issues, please let me know then. And I will get back to you soon. 

Thank you!
