### ISSUE TITLE
anchor link reload the page in nested ea advanced tabs setup

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#721]
I got a nested ea advanced tabs setup like this

```
                                                            SINGLE PAGE

         TAB1                               TAB2                          TAB3                                TAB4
           |                                 |                              |                                  |
           |                                 |                              |                                  |
           |                                 |                              |                                  |
TAB11   TAB12   TAB13   TAB14       TAB21   TAB22   TAB23   TAB24       TAB31   TAB32   TAB33   TAB34        TAB41   TAB42   TAB43   TAB44
```

on each sub tabs (like 12, 24, 41 etc.) I have multiple anchor links to other sub tabs, they're all working but those links reload the page each time and it's not optimal.

the anchor links have this format
`example.com/samepageurl/#tabid`

because when I try without the slash
`example.com/samepageurl#tabid`

it wont work

**Comment by sadmansakibnadvi** [comment]
Hello @Azertooth ,

Greetings.

Well, `example.com/samepageurl/#tabid` is the default behavior format for any browser. It is not possible to use an anchor link without the slash. That's why it doesn't work.

Hope you understand. Thank you.

**Comment by Azertooth** [comment]
> Hello @Azertooth ,
> 
> Greetings.
> 
> Well, `example.com/samepageurl/#tabid` is the default behavior format for any browser. It is not possible to use an anchor link without the slash. That's why it doesn't work.
> 
> Hope you understand. Thank you.

thank you for joining the conversation @sadmansakibnadvi and clearing up my doubt on the url format, but what about the page reloading each time an anchor link is clicked, even if the anchor is on the same page?
