### ISSUE TITLE
Can't remove scrollbar from elementor calendar on mobile view

### ISSUE THREAD

**Issue by Azertooth** [WPDevelopers/essential-addons-for-elementor-lite#722]
I want to remove [this](https://i.postimg.cc/SxbnjZ16/immagine.png) scrollbar, extending the addon through the bottom, to show the full calendar without scrolling. I tried with every addon margin but without success

**Comment by IftekharPial** [comment]
Hello there,

Sorry for the inconvenience,

You can use this CSS code to resolve your issue with the scrollbar.

.fc-scroller.fc-day-grid-container {
height: auto !important;
}


You can check this [video](https://d.pr/v/UK63lg) for a better understanding

Video link: https://d.pr/v/UK63lg


For more details on how to add custom CSS, you can check out this doc: https://essential-addons.com/elementor/docs/faq/apply-custom-css-elements/

I hope this will help you out. 

Thank you

**Comment by Azertooth** [comment]
that solved my issue, thank you!
