### ISSUE TITLE
See attached, when I activate essential addons my website crashes

### ISSUE THREAD

**Issue by dddn1328** [WPDevelopers/essential-addons-for-elementor-lite#723]
Fatal error: Uncaught Error: Class 'Elementor\Scheme_Typography' not found in /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/essential-addons-elementor/elements/instagram-gallery/instagram-gallery.php:394 Stack trace: #0 /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2280): Elementor\Widget_Eael_Instagram_Feed->_register_controls() #1 /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(494): Elementor\Controls_Stack->init_controls() #2 /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/elementor/includes/base/widget-base.php(177): Elementor\Controls_Stack->get_stack() #3 /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(300): Elementor\Widget_Base->get_stack() #4 /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(23 in /home/customer/www/justsomewanderlust.com/public_html/wp-content/plugins/essential-addons-elementor/elements/instagram-gallery/instagram-gallery.php on line 394

**Comment by rudlinkon** [comment]
Hello there,

Sorry for the inconvenience,

You are using a very old version of our plugin. Please update to the latest version and check again.
EA Lite Latest Version is `5.1.2` and your version is `4.3.8`
EA Pro Latest Version is `5.1.1` and your version is `2.14.0`

I hope this will help you out.

Thank you

**Comment by abid112** [comment]
Hi @dddn1328 ,

Please make sure to update Essential Addons for Elementor FREE(**v5.1.2**) and PRO(**v5.1.1**) to resolve this issue.

Thank you!
