### ISSUE TITLE
Post carousel mobile issue

### ISSUE THREAD

**Issue by BeenishIkhlaq** [WPDevelopers/essential-addons-for-elementor-lite#724]
I used EA Post carousel and set 1 post on mobile, after reloading it shows 1 post but after reloading the 2nd time, 3 posts show on mobile. I can't understand what is the problem
![Screenshot_3](https://user-images.githubusercontent.com/51711666/170214584-32c9004e-50ca-4510-a8d2-e7714c43e35f.png)
?

**Comment by sadmansakibnadvi** [comment]
Hi there,


Sorry for the inconvenience caused.

Please Follow this: From **Dashboard go to Elementor > Settings > Experiments > Additional Custom Breakpoints > Inactive and save settings.** Retry now once.

Hope your issue will be fixed. Let us know how it goes.

Thanks!

**Comment by BeenishIkhlaq** [comment]
Thanks
