### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by nimaam** [WPDevelopers/essential-addons-for-elementor-lite#726]
Dear friend, I should thankful for this nice job, but in Woo-Product-Carousel if we need to put a text instead of the icons? or change the icons? what should we do?
is it possible to add this feature too.

**Comment by amitbarai013** [comment]
Hi @nimaam ,
Hope you are doing well.

In the **Woo Product Carousel**, you can add a text instead of the icon but you can add that using the custom CSS. Please let us know if you want to put text instead of which icon, and we will assist you.

Thank you.
