### ISSUE TITLE
Edit Login | Register Form widget > missing WPML language strings

### ISSUE THREAD

**Issue by FlyThePlanet** [WPDevelopers/essential-addons-for-elementor-lite#728]
I've tried to use the Edit Login | Register Form widget on a multi languages website, but 2 key language strings are missing:
- the Content > General > "Redirect for Logged-in Users" URL
- and the Content > General > Login Form General > "Custom Lost Password" URL

The only URL field available for translation/adjustment for a secondary language is Content > Login Form Options > "Redirect After Login" URL.

This lack is even blocking for the Custom Lost Password URL as the whole hyperlink becomes useless for all secondary languages. Indeed the URL used is not even the one set in the widget, for the main language, for all secondary languages the URL used is just the website homepage. Users can't even reach the Lost password page anymore 👎 

So please, could you fix those 2 issues ASAP, especially for the Custom Lost Password URL?
As awaiting the fix, I really can't use this widget.

Thanks!

**Comment by FlyThePlanet** [comment]
Hi,

Is this issue supposed to be fixed with the 5.1.9?

> Fixed: EA Login/Register Form | Added WPML Support for the missing strings

Because I don't know which strings this is referring to, but I can't find the 2 expected in the WPML language strings: "Redirect for Logged-in Users" & "Custom Lost Password"

**Comment by arrasel13** [comment]
Hi @FlyThePlanet,

Hope you are doing well. Yes, we have already fixed and released it on the latest version.
You just need to remove the **HTTP** or **HTTPS** from the given URL. You can check this URL that how to put the URL: https://d.pr/v/3FUQz0

After that, please retry to translate your page with WPML, and you will get the option. If you put the **HTTP** or **HTTPS** on your URL, it will not work correctly. Please check once without **HTTP** or **HTTPS** and let us know the update.

Thanks for your patience!

**Comment by FlyThePlanet** [comment]
Sorry but it's clearly not working.

There are 3 fields to test:
- Content > General > Redirect for Logged-in Users > URL field
- Content > General > Login Form General > Custom Lost Password URL
- Content > Login Form Options > Redirect After Login > URL field (was already working in the past!)

**Test 1 : fill-in Redirect for Logged-in Users > URL field only with "./test/"**
1/ When we enable "Redirect for Logged-in Users" the plug-in set by default in the URL field below "https://www.myWebsite.com". It's really not consistent with your instructions
2/ After entering "./test/" only, the Redirect for Logged-in Users > URL field never shows up in the language string to translate!

**Test 2 : fill-in Custom Lost Password URL only with "./test/"**
1/ This works fine. The Custom Lost Password URL field language string shows up!
2/ BUT... whether you enter "./test/" or "https://www.myWebsite.com/test/" it's the same. It works fine in both cases.

**Test 3 : fill-in Redirect After Login > URL field only with "./test/"**
1/ When we enable "Redirect After Login" the plug-in set by default in the URL field below "https://www.myWebsite.com/wp-admin/". It's really not consistent with your instructions!
2/ Apart from the issue above, it was working fine in the past and still works fine now with the 5.1.9. The Redirect After Login > URL field language string shows up for translation!
3/ BUT... whether you enter "./test/" or "https://www.myWebsite.com/test/" it's the same. It works fine in both cases.

**Test 4 : fill-in the 3 URL fields with "./test1/", "./test2/" & "./test3/"**
1/ In this case it's getting worst than the individual tests: only "Redirect After Login > URL field" shows-up with the "./test3/" language string to translate. The 2 others don't show up: the 1st one that never shows up anyway (so it's not a surprise), BUT ALSO the 2nd one, Custom Lost Password URL with the "./test2/" language string doesn't show up! When this field is fill-in at the same time as the 2 others (or at least one of the 2 other, I've not tested), then its language string doesn't show up for translation!

Conclusions:
- Field 1 never show up for translation / the default value includes https
- Field 2 shows up ONLY if it's the only URL to translate, otherwise doesn't show up as well / including http/https or not makes no difference
- Field 3 always shows up for translation / the default value includes https / including http/https or not makes no difference
- In any case, adding http or https seems to have no influence on the fact that a field shows up or not for translation

**Comment by arrasel13** [comment]
Hi @FlyThePlanet,

Sorry for the inconvenience caused. Yes, got the same issue as you mentioned. I am checking the issue with our Dev Team again. We will fix and update you as soon as possible. Please allow us time.

Thanks for your patience!

**Comment by arrasel13** [comment]
Hi @FlyThePlanet,

Hope you are doing well.
We have fixed the issue. You can check with this branch: https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/2224 and then retry once. Please clear the WPML cache as well. On the below-shared screen record, you will get to know how to clear the WPML cache.

I have tried it on my site, and it is working well. You can check this screen record: https://d.pr/v/dXoWJA

Let us know how it goes. Thanks!

**Comment by FlyThePlanet** [comment]
Ok. How do I get an installable .zip from GitHub?
The 5.1.9 release is not what I need.

**Comment by rudlinkon** [comment]
> Ok. How do I get an installable .zip from GitHub?

https://github.com/WPDevelopers/essential-addons-for-elementor-lite/archive/refs/heads/2224.zip

**Comment by FlyThePlanet** [comment]
Sorry @rudlinkon , I installed this version on my test environment but I realized this test environment does not have WPML. And I'll have no time on a short term to install a test environment with WPML.

So please go ahead, if you have properly tested it and you think it works fine, publish the fix in the next release and I'll test the production version on my website that has WPML (I have only 1 website with WPML, the others don't have it, as well as the test environment).

Thanks!

**Comment by rudlinkon** [comment]
> Sorry @rudlinkon , I installed this version on my test environment but I realized this test environment does not have WPML. And I'll have no time on a short term to install a test environment with WPML.
> 
> So please go ahead, if you have properly tested it and you think it works fine, publish the fix in the next release and I'll test the production version on my website that has WPML (I have only 1 website with WPML, the others don't have it, as well as the test environment).
> 
> Thanks!

Okay, we will do that.

**Comment by arrasel13** [comment]
Hi @FlyThePlanet,

Hope you are doing well. We have already fixed this on our latest release. Please check with the latest version plugin and then retry once.

Let us know if you are facing any issues. Thanks!

**Comment by FlyThePlanet** [comment]
> Hope you are doing well. We have already fixed this on our latest release. Please check with the latest version plugin and then retry once.

In which version? The 5.2.4?
If it's this one, sorry there's no change at all. All the behaviors described above are still the exact same, even after clearing the WPML cache.

**Comment by IftekharPial** [comment]
Hello there

Hope you are doing well.

Sorry for the delayed response. You will be glad to know that the fixed has been included in our latest update of Essential Addons

So Please update the latest version of Essential Addons for Elementor v.5.8.7.

After the update, if you are still facing the issue that means It might be a caching issue. So can you please try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/8467Wx

If the issue still persists then, It is possible that your browser cache is not updating properly.

Please kindly clear the cache of your browser and hard refresh your browser with (cmd/Ctrl) +Shift + R.

If you are using a caching plugin, you need to purge the cache from your plugin option and then deactivate the caching plugin temporally so that the new update could take effect.

Also, you could check this on a different browser.

Hopefully, it will fix the issue.

Let me know how it goes.
Thanks
