### ISSUE TITLE
Post Grid database error

### ISSUE THREAD

**Issue by NickolasGuers** [WPDevelopers/essential-addons-for-elementor-lite#730]
Using the Post Grid module to display an event post type creates a database error.  Attached is a screenshot from my sql debugging if thats helpful. Could you kindly explain if this is an issue with Post Grid or I need to contact  the owners of "tribe_events" post type.

```
WordPress database error Unknown column 'wp_postmeta.meta_value' in 'field list' for query 
			SELECT SQL_CALC_FOUND_ROWS DISTINCT wp_posts.*, MIN(wp_postmeta.meta_value) as EventStartDate, MIN(tribe_event_end_date.meta_value) as EventEndDate
			FROM wp_posts  LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) LEFT JOIN wp_postmeta as tribe_event_end_date ON ( wp_posts.ID = tribe_event_end_date.post_id AND tribe_event_end_date.meta_key = '_EventEndDate' ) 
			WHERE 1=1  AND ( 
  wp_term_relationships.term_taxonomy_id IN (9)
) AND wp_posts.post_type = 'tribe_events' AND ((wp_posts.post_status = 'publish'))
			GROUP BY wp_posts.ID
			ORDER BY wp_posts.post_date ASC
			LIMIT 0, 1 
```
![debug](https://user-images.githubusercontent.com/33167572/177375180-4f1936b3-4680-412c-b53d-d32e4950bf88.png)

**Comment by onlykawshar** [comment]
Hello @NickolasGuers, 

I hope you are doing well. 

I am sorry to hear about this inconvenience. I have tried to recreate the same issue that you are having but couldn't get the same. I request you to contact the owner of "tribe_events" post type. I hope you will get some better support from there. Let me know what you get from there. 

Thank you.
