### ISSUE TITLE
Plugin prevents woocommerce cross sell from showing.

### ISSUE THREAD

**Issue by mdpknight** [WPDevelopers/essential-addons-for-elementor-lite#731]
Activating this plugin causes cross sells in woocomerce from showing in the cart. Turning on wp-debug shows no errors and the error_log shows nothing either.

**Comment by rudlinkon** [comment]
already fixed this issue on the `2207` branch and now it is the testing phase, after testing is done it will be released thank you.

**Comment by robinwpdeveloper** [comment]
Mentioned branch `2207` is already released. 
Closing this ticket as completed.

If you still have the issue feel free to reopen.
