### ISSUE TITLE
Plugin prevents certain styles from loading

### ISSUE THREAD

**Issue by PixelForm** [WPDevelopers/essential-addons-for-elementor-lite#733]
With the plugin active it prevents styles from my theme and elementor, which has css variables, from loading. It results in broken site styling. Is there a way to solve it? Plus I'm using the latest version.

P.s. The live chat on wpdelvelopers official website on the support page doesn't work.

**Comment by khan-rafin-ahmed** [comment]
Hi @PixelForm,

Can you please tell us the theme you are using? You can share your System Info from Elementor -> Tools as well.

Thank you!

**Comment by khan-rafin-ahmed** [comment]
Hi @PixelForm,

You can aslo try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/iBccDw

Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools -> General as well. Check out this screenshot: https://d.pr/i/N6WC1d

If the issue still persists, please try clearing your browser cache (by pressing shift+ctrl+R) or try another browser too.

**Comment by PixelForm** [comment]
> Hi @PixelForm,
> 
> You can aslo try doing this following: To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/iBccDw
> 
> Also, make sure to Regenerate Files from wp-admin -> Elementor -> Tools -> General as well. Check out this screenshot: https://d.pr/i/N6WC1d
> 
> If the issue still persists, please try clearing your browser cache (by pressing shift+ctrl+R) or try another browser too.

I am using Riode theme from Themeforest. I regenerated the CSS already but doesn't work and tried putting it inline but doesn't work either

**Comment by arrasel13** [comment]
Hi @PixelForm,

Sorry for the inconvenience caused.
We need to check this issue more deeply. Please create a ticket here: https://wpdeveloper.com/support/new-ticket

Our Technical support team will check and get back to you as soon as possible.

Thanks!

**Comment by arrasel13** [comment]
@PixelForm 

Yes, you can still create a support ticket. Our team will get back to you as soon as possible.

**Comment by PixelForm** [comment]
Alright, thanks for your help
