### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by svika** [WPDevelopers/essential-addons-for-elementor-lite#736]
Peace,

I have a premium subscription. I can't update the plugin. In addition, your system does not recognize my email. What to do?

My email is: eretz.hatzvi@gmail.com

**Comment by onlykawshar** [comment]
Hello @svika, 

I hope you are doing well. It seems you have created a support ticket, and one of my colleagues replied there. Can you please check your email to reply back your feedback? 

Thank you

**Comment by arrasel13** [comment]
Hi @svika 

Hope you are doing well.
From your support ticket got that your issue is already fixed. I am closing this topic.

Have a good day!
