### ISSUE TITLE
Used js libraries

### ISSUE THREAD

**Issue by RabbiArt** [WPDevelopers/essential-addons-for-elementor-lite#741]
Using the Elementor Essential Addons Plugin and found some Security Hotspots within a Sonarcloud Analysis of the code of the plugin.
They are caused by the js libraries moment.js, isotope.pkgd.js and calendar-main.js which are used and locally included. It seems (at least for the momentum.js lib) that there are old versions enqueued in the code. The current maintained versions of the js libs should have fixed this issues.

**Comment by ashikur-23** [comment]
Hi @RabbiArt 

Hope you're doing well, and Sorry for not getting back to sooner.

Our DEV team has already updated calendar.js and moment.js in the recent version.

Could you please check that again and let us know if any issues still exist.

We are looking forward to hearing back from you.

Thanks & Regards
