### ISSUE TITLE
Filterable Menu no longer responsive

### ISSUE THREAD

**Issue by who519** [WPDevelopers/essential-addons-for-elementor-lite#743]
Hi I am using the Astra theme with Elementor and your plugin and love the filterable gallery, had to code another version myself years ago, this is much easier. The issue I am having is that it is no longer responsive it is just keeping the gallery 3 wide all the way down. Is this a known issue?

Edit: Hold off on this one...it seems to be working, but has gone in and out, I need to browser test a bit more to see if the issue is on my end.

Edit2: Nope still having problems, the gallery looks fine in elementor editor and then it doesn't and doesn't work at all when I view the site. I have turned off all my other plugins and even removed my custom CSS, it did nothing. I also started a brand new gallery on another page without changing any of the settings and the responsive adjustments still didn't work. Basically it is just shrinking the gallery down without accessing any of the breakpoints. So each item is staying 33%.

**Comment by rudlinkon** [comment]
Hi @who519 

Hope you're doing well, our DEV team has already fixed that issue on a [dev branch](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/2609).

Could you please check that again and let us know if any issues still exist?

We are looking forward to hearing back from you.

Thanks & Regards

**Comment by who519** [comment]
Thank you for the quick response, and pardon my ignorance, but do I just need to update the plugin? Or Do I need to pull that branch somehow?

**Comment by amitbarai013** [comment]
Hi @who519 ,
Hope you are doing well.

I have checked this with the Dev version and found it fixed on my end. Please check this screencast: https://d.pr/v/qq02rM 

You can pull the 2609 branch from [this dev branch](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/tree/2609).

Also, you can download the **Essential Addons for Elementor** plugin from here: https://d.pr/f/HgmDOo

While installing this plugin, you just replace the previously installed one.

After installing, please regenerate assets. To regenerate assets, you can go to **wp-admin -> Essential Addons** then, switch to the **‘Tools’** tab and hit the **‘Regenerate Assets’** button. Check out this screenshot: https://d.pr/i/iBccDw

Also, make sure to Regenerate Files from **wp-admin -> Elementor -> Tools -> General** as well. Check out this screenshot: https://d.pr/i/N6WC1d

If the issue still persists, please try clearing your browser cache (by pressing _shift+ctrl+R_) or try another browser too.

Let me know how it goes. 
Thank you.

**Comment by who519** [comment]
Thank you so much for the thorough response @amitbarai013 ! Totally worked, really appreciate the quick and effective response from you and your team. Five stars! Love the plugin.

**Comment by amitbarai013** [comment]
Hi @who519 ,

I am glad to know that it resolved your issue and we were able to help, please feel free to contact our support anytime you need help, we are always here to help. 

If you don’t mind me asking, could you do me a favor, and spend 30-sec to review us following this link, this will help us to serve better. 

Thank you in advance! 

Link to review - http://wpdeveloper.com/review-essential-addons-elementor

Have a good day! :)
