### ISSUE TITLE
Filterable Gallery - Essential Addons

### ISSUE THREAD

**Issue by QuentinChaumy** [WPDevelopers/essential-addons-for-elementor-lite#748]
Hello, 

I have some issue where the filterable gallery was non viewable on the live website ... It work well when i'm working in elementor, but when I disconnect i can't see the filterable gallery ... do you have some advice ?

thanks.

**Comment by rudlinkon** [comment]
Hi @QuentinChaumy, Could you please provide some screenshots or a screen recording? So that we can identify the issue and take action to fix it.

Thank you,
Linkon Miyan

**Comment by IftekharPial** [comment]
Hello again @QuentinChaumy,

Sorry for the inconvenience.

We did not hear from you since our last conversation.

Could you please let us know if you are still having the issue?
So that we could try to solve your issue.

We are waiting for your response.

Thank you.

**Comment by IftekharPial** [comment]
Hello again

Hope you are doing well.

About your issue, We still haven’t heard back from you. So, I am assuming your issue has been resolved. I am resolving this topic.


Have a nice day!
