### ISSUE TITLE
Essentail Addons Product Grid - Load More button becomes non responsive on mobile

### ISSUE THREAD

**Issue by HSaim** [WPDevelopers/essential-addons-for-elementor-lite#749]
Hi,

I'm currently utilizing Essential Addons V:5.8.6. The Product Grid occasionally becomes unresponsive on mobile view, causing inconvenience. Your assistance in resolving this issue would be greatly appreciated. The problem is affecting my customers' experience negatively. While I have only one grid per page, I am using multiple product grids across my website.

Regards,
Habiba Saim

**Comment by NayeemNipun** [comment]
Hi @HSaim,
Greetings. Hope you are doing well. 

Can you please share any screenshots or screencast so that I can check the issue and assist you further? Also, you can share the exact URL with the issue as well. 

Thanks and Regrads.

**Comment by NayeemNipun** [comment]
Hi @HSaim,
Greetings. Hope you are doing well.

Can you please share any screenshots or screencast so that I can check the issue and assist you further? Also, you can share the exact URL with the issue as well.

Thanks and Regards.

**Comment by HSaim** [comment]
Hello,

I've observed this issue occurring three times within the past week. It seems that whenever there's an impending plugin update, this problem arises. Just today, while a WordPress update was pending, I received a report about an unresponsive "Load More" button. Oddly, there appears to be no direct correlation between Essential Addons (EA) and updates for other plugins. However, after updating the plugin, the button starts functioning again. Interestingly, I don't make any changes except for the plugin update. As of now, all "Load More" buttons are operational, so I'm unable to provide a screenshot. Nevertheless, I can share the screenshot of a recent complaint I received a few hours ago.

Website URL: https://gemsbyuzma.com
The Product Grid is implemented on the landing page, all categories pages, and the shop page.
![Load More Button Issue](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/assets/16533492/9c40512d-4c9b-427a-9b53-7962af1536ca)

**Comment by NayeemNipun** [comment]
Hi @HSaim, 

Thanks for your details reply. The issue you faced sometimes could be caused for caching mechanism. For future reference, I would like to suggest you keep all plugins, themes, and WordPress core updated and purge all cache after updating any plugin. 

Also, I will definitely forward this issue to our Dev Team for a deep investigation and take necessary steps if they found anything regarding this. 

Thanks and Regards.

**Comment by HSaim** [comment]
Hello,

Thank you for your response. However, it's not feasible for me to constantly monitor the website and updates.

Interestingly, the Load More button worked perfectly last night, but this morning it became unresponsive again without any pending updates. Although purging the pages resolved the issue temporarily, this isn't a sustainable solution. Strangely, the problem appeared on both my phone and laptop today. I've attached relevant videos for your reference.

I would greatly appreciate it if my concern could be addressed with priority. While I'll continue to monitor the website's behavior, my requirement is to overcome this limitation and ensure independent functionality.

Best regards,

Habiba Saim


https://github.com/WPDevelopers/essential-addons-for-elementor-lite/assets/16533492/1c350f08-6cb1-44b1-b5ab-a2dde47f9382


https://github.com/WPDevelopers/essential-addons-for-elementor-lite/assets/16533492/0ab27990-756f-4a3b-8b18-e7b42b756431

**Comment by HSaim** [comment]
Hi,

Any update about the issue I am facing?

**Comment by NayeemNipun** [comment]
Hi @HSaim, 
Greetings. Hope you are doing well. 

Our Dev Team is already aware of this and they will fix the issue soon and will be released in future releases. Thanks a lot for your concern. I really appreciate this. 

Thanks.

**Comment by HSaim** [comment]
Hi,

I greatly appreciate your response. I'm eagerly anticipating the resolution
of the bug.

Regards,
Habiba Saim

**Comment by HSaim** [comment]
Hello,

I find myself consistently encountering the issue of an unresponsive "Load More" button on a daily basis. Unfortunately, the most recent update of EA did not provide a solution to this problem. Could you please provide an estimated timeframe for when this issue might be addressed? Given that customers have little patience for such bugs, resolving this problem with high priority is crucial.

Thank you.

**Comment by NayeemNipun** [comment]
Hi @HSaim, 
Greetings. Hope you are doing well.

Regarding your issue, I am delighted to let you know that our Dev Team has fixed the issue in a Dev version of Essential Addons for Elementor - lite. For your convenience, I am sharing the download link of the fixed Dev version below. I would like to suggest you to download the Dev version, install it manually and check it on your end. 

Download link - https://d.pr/f/9LnzLw

Hope this will help you out. Please let me know how it goes. We are always here to assist you. 

Thanks and Regards.

**Comment by HSaim** [comment]
Thanks. I will install and update you soon. Hope it is a verified version
and it won't damage my website.

Regards,
Habiba Saim

**Comment by rudlinkon** [comment]
> 

Yes, this version is made by our internal team you can feel free to use it.

**Comment by rudlinkon** [comment]
> Thanks. I will install and update you soon. Hope it is a verified version and it won't damage my website. Regards, Habiba Saim


Yes, this version is made by our internal team you can feel free to use it.

**Comment by HSaim** [comment]
Ok thanks for the support and prompt response.
Regards,
Habiba Saim

**Comment by HSaim** [comment]
I'm really frustrated at the moment. I've installed the latest EA official
update, and the Load More button is not working at all, neither on the
desktop nor on mobile. I urgently require the previous version.

Regards,
Habiba Saim


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by NayeemNipun** [comment]
Hi there, 
Really sorry for the inconvenience. Regarding your query, the Load More button issue fixing was released on the latest version. It should work perfectly. It seems strange that it didn't work for you. Really sorry again. 

I would like to request you to update the Essential Addons for Elementor FREE and PRO (if you are using) and try regenerate assets for both Elementor and Essential Addons for Elementor and check again. Check out these screenshots for regenerate assests: https://d.pr/i/iBccDw and https://d.pr/i/N6WC1d
Also, please make sure you clear your website and browser cache before checking. 

If the issue still persists, I would like to request you not to revert back to the old version and let us know so that we can check the issue and help you out. 

Please let me know how it goes. 

Thanks and Regards.

**Comment by HSaim** [comment]
Hello,

I apologize for the delay in my response. I've recently updated EA to
version 5.8.8 and followed your provided instructions. I'm pleased to
report that the Load More button is now working as intended. I'm hopeful
that it will remain responsive without the need for frequent cache purging.
I appreciate your assistance, and I'll certainly provide an update if any
issues arise. Otherwise, the absence of any news is a positive outcome.
Thank you!

Regards,
Habiba Saim

**Comment by NayeemNipun** [comment]
Hi @HSaim,

Really happy to know that. Please feel free to contact our support anytime you need help, we are always here to assist you.

If you don't mind me asking if you like our plugin and also our support, could you do me a favor, and spend 30-sec to reviewing us following this link, this will help us to serve better.
​Link to review - https://wordpress.org/support/plugin/essential-addons-for-elementor-lite/reviews/#new-post

Please feel free to reach out anytime if you have any other issues or queries. We are always here to assist you. 
​
​Thanks and Regards.
