### ISSUE TITLE
Problem with "Login | Register" Form after 5.8.8

### ISSUE THREAD

**Issue by sudozk** [WPDevelopers/essential-addons-for-elementor-lite#750]
Hello, we are facing problem after automatic update _Essential Addons for Elementor_ from 5.8.7 to 5.8.8

After the user logs in via the form on the page, the following error is displayed:
Warning: Undefined array key **"enable_register_recaptcha"** in /wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/**Login_Registration.php on line 138**

```
Warning: Undefined array key "enable_register_recaptcha" in /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php on line 138

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php:138) in /data/web/virtuals/254388/virtual/www/domains/domain/wp-includes/pluggable.php on line 1093

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php:138) in /data/web/virtuals/254388/virtual/www/domains/domain/wp-includes/pluggable.php on line 1094

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php:138) in /data/web/virtuals/254388/virtual/www/domains/domain/wp-includes/pluggable.php on line 1095

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php:138) in /data/web/virtuals/254388/virtual/www/domains/domain/wp-includes/pluggable.php on line 1435

Warning: Cannot modify header information - headers already sent by (output started at /data/web/virtuals/254388/virtual/www/domains/domain/wp-content/plugins/essential-addons-for-elementor-lite/includes/Traits/Login_Registration.php:138) in /data/web/virtuals/254388/virtual/www/domains/domain/wp-includes/pluggable.php on line 1438
```

We do not have recaptcha enabled on the form, we tried to enable/disable it, but the problem continues.

It looks like line 138 in Login_Registration.php is mentioned in the error message was modified in the commit https://github.com/WPDevelopers/essential-addons-for-elementor-lite/commit/67b6e62dbbb209658f5a800633f62190dd4101df (login recaptcha updated) which is new in the latest version 5.8.8

https://github.com/WPDevelopers/essential-addons-for-elementor-lite/blob/67b6e62dbbb209658f5a800633f62190dd4101df/includes/Traits/Login_Registration.php#L138

Can you please advise which direction to look for a solution?

Thanks

**Comment by IftekharPial** [comment]
Hello @sudozk 

Sorry for the inconvenience, You will be glad to know that Our Dev team has already fixed the ‘Undefined array key’ error notice issue and it will be released very soon.

In the meantime, we have a Dev version containing the fix regarding the issue, you can find that here : https://d.pr/f/mveEvg

Please make sure to make a Backup of your site before any Updates.

Note: Please Regenerate the asset after updating the Dev version
To regenerate assets, you can go to wp-admin -> Essential Addons then, switch to the ‘Tools’ tab and hit the ‘Regenerate Assets’ button. Check out this screenshot: https://d.pr/i/FuLkYy

Hopefully, it will solve your issue
Let me know how it goes
Thanks

**Comment by IftekharPial** [comment]
Hello again @sudozk 

Please let us know the status after updating the fix.

If it’s working properly then please provide us a confirmation and if you are still facing any issues then please share the details so that we can investigate and assist accordingly.

Looking forward to hearing from you 

Thanks

**Comment by sudozk** [comment]
Hello, thanks for Dev verions. We just tried it and problem is solved - no error after login via custom form. 
Thanks and have a nice day!
