### ISSUE TITLE
Wordpress issues after latest update.

### ISSUE THREAD

**Issue by timparker14** [WPDevelopers/essential-addons-for-elementor-lite#755]
![Kazam_screenshot_00151](https://github.com/WPDevelopers/essential-addons-for-elementor-lite/assets/25883873/a8479e08-d320-49c7-ac0d-41d57f5f8941)

WordPress issues after 5.9.6 update

**Comment by timparker14** [comment]
I have deactivated and reactivated all plugins. Problem remains.

**Comment by timparker14** [comment]
If I deactivate Essential Addons for Elementor the issues clear.

**Comment by rudlinkon** [comment]
Hello @timparker14,
Thank you for your report, we have already fixed and released it. Please update the plugins and check them.

**Comment by timparker14** [comment]
5.9.7 is all good. Thank you.
