### ISSUE TITLE
Post Carousel Widget custom query not showing posts with tag and/or showing duplicate posts with tag

### ISSUE THREAD

**Issue by saawood13** [WPDevelopers/essential-addons-for-elementor-lite#761]
I have a post widget that I want to show posts within a category (Blogs) that also have a specific tag. I have two posts within the blog category tagged as "General" . When I add the tag query "General" it shows one of the posts three times and the other post not at all. I have tried removing the general tag from the post that shows up three times and now nothing shows up. I have checked the tags everything seems correct?

**Comment by NayeemNipun** [comment]
Hi @saawood13, 
Greetings. Hope you are doing well. Really sorry for the delay in reply due to the weekend. 

Regarding your query, please allow us some time to check the issue from our end and I will be back to you ASAP with an update. In the meantime, you can share the exact URL of the issue so that it helps me to investigate. 

Thanks and Regards.

**Comment by NayeemNipun** [comment]
Hi @saawood13,
Greetings. Hope you are doing well. 

Regarding your query, I have checked the issue you have mentioned and it seems you have **Infinite Loop** enabled from the **EA Post Carousel** - carousel settings. When you have enabled that function it triggers the infinite loop and duplicate posts to fill up the blank posts from your query for visible items. As you set up the visible items to 3 and your selected tags have only one post, it duplicated that single posts to show as infinite loop. 

You can disable the infinite loop to show the one post from your tags. For reference please check this screencast - https://d.pr/v/rZYtJf

Hope this will help you out. Please let me know how it goes. I am here to assist you further. 

Thanks and Regards.
